// Code generated by cmd/cgo; DO NOT EDIT.

package main

import "unsafe"

import "syscall"

import _cgopackage "runtime/cgo"

type _ _cgopackage.Incomplete
var _ syscall.Errno
func _Cgo_ptr(ptr unsafe.Pointer) unsafe.Pointer { return ptr }

//go:linkname _Cgo_always_false runtime.cgoAlwaysFalse
var _Cgo_always_false bool
//go:linkname _Cgo_use runtime.cgoUse
func _Cgo_use(interface{})
//go:linkname _Cgo_keepalive runtime.cgoKeepAlive
//go:noescape
func _Cgo_keepalive(interface{})
//go:linkname _Cgo_no_callback runtime.cgoNoCallback
func _Cgo_no_callback(bool)
type _Ctype__GoBytes_ []byte

type _Ctype__GoString_ string

type _Ctype___atomic_wide_counter [8]byte

type _Ctype___be16 = _Ctype___u16

type _Ctype___be32 = _Ctype___u32

type _Ctype___be64 = _Ctype___u64

type _Ctype___pthread_list_t = _Ctype_struct___pthread_internal_list

type _Ctype___socklen_t = _Ctype_uint

type _Ctype___ssize_t = _Ctype_long

type _Ctype___u16 = _Ctype_ushort

type _Ctype___u32 = _Ctype_uint

type _Ctype___u64 = _Ctype_ulonglong

type _Ctype___uint16_t = _Ctype_ushort

type _Ctype___uint32_t = _Ctype_uint

type _Ctype___uint64_t = _Ctype_ulong

type _Ctype___uint8_t = _Ctype_uchar

type _Ctype_char int8

type _Ctype_in_addr_t = _Ctype_uint32_t

type _Ctype_in_port_t = _Ctype_uint16_t

type _Ctype_int int32

type _Ctype_intgo = _Ctype_ptrdiff_t

type _Ctype_long int64

type _Ctype_nfds_t = _Ctype_ulong

type _Ctype_pthread_cond_t [48]byte

type _Ctype_pthread_mutex_t [40]byte

type _Ctype_ptrdiff_t = _Ctype_long

type _Ctype_sa_family_t = _Ctype_ushort

type _Ctype_short int16

type _Ctype_size_t = _Ctype_ulong

type _Ctype_socklen_t = _Ctype___socklen_t

type _Ctype_ssize_t = _Ctype___ssize_t

type _Ctype_struct___pthread_internal_list struct {
	__prev	*_Ctype_struct___pthread_internal_list
	__next	*_Ctype_struct___pthread_internal_list
}

type _Ctype_struct__ibv_device_ops struct {
	_dummy1	*[0]byte
	_dummy2	*[0]byte
}

type _Ctype_struct_ibv_ah_attr struct {
	grh		_Ctype_struct_ibv_global_route
	dlid		_Ctype_uint16_t
	sl		_Ctype_uint8_t
	src_path_bits	_Ctype_uint8_t
	static_rate	_Ctype_uint8_t
	is_global	_Ctype_uint8_t
	port_num	_Ctype_uint8_t
	_		[1]byte
}

type _Ctype_struct_ibv_cm_id _cgopackage.Incomplete

type _Ctype_struct_ibv_comp_channel struct {
	context	*_Ctype_struct_ibv_context
	fd	_Ctype_int
	refcnt	_Ctype_int
}

type _Ctype_struct_ibv_context struct {
	device			*_Ctype_struct_ibv_device
	ops			_Ctype_struct_ibv_context_ops
	cmd_fd			_Ctype_int
	async_fd		_Ctype_int
	num_comp_vectors	_Ctype_int
	_			[4]byte
	mutex			_Ctype_pthread_mutex_t
	abi_compat		unsafe.Pointer
}

type _Ctype_struct_ibv_context_ops struct {
	_compat_query_device	*[0]byte
	_compat_query_port	*[0]byte
	_compat_alloc_pd	*[0]byte
	_compat_dealloc_pd	*[0]byte
	_compat_reg_mr		*[0]byte
	_compat_rereg_mr	*[0]byte
	_compat_dereg_mr	*[0]byte
	alloc_mw		*[0]byte
	bind_mw			*[0]byte
	dealloc_mw		*[0]byte
	_compat_create_cq	*[0]byte
	poll_cq			*[0]byte
	req_notify_cq		*[0]byte
	_compat_cq_event	*[0]byte
	_compat_resize_cq	*[0]byte
	_compat_destroy_cq	*[0]byte
	_compat_create_srq	*[0]byte
	_compat_modify_srq	*[0]byte
	_compat_query_srq	*[0]byte
	_compat_destroy_srq	*[0]byte
	post_srq_recv		*[0]byte
	_compat_create_qp	*[0]byte
	_compat_query_qp	*[0]byte
	_compat_modify_qp	*[0]byte
	_compat_destroy_qp	*[0]byte
	post_send		*[0]byte
	post_recv		*[0]byte
	_compat_create_ah	*[0]byte
	_compat_destroy_ah	*[0]byte
	_compat_attach_mcast	*[0]byte
	_compat_detach_mcast	*[0]byte
	_compat_async_event	*[0]byte
}

type _Ctype_struct_ibv_cq struct {
	context			*_Ctype_struct_ibv_context
	channel			*_Ctype_struct_ibv_comp_channel
	cq_context		unsafe.Pointer
	handle			_Ctype_uint32_t
	cqe			_Ctype_int
	mutex			_Ctype_pthread_mutex_t
	cond			_Ctype_pthread_cond_t
	comp_events_completed	_Ctype_uint32_t
	async_events_completed	_Ctype_uint32_t
}

type _Ctype_struct_ibv_device struct {
	_ops		_Ctype_struct__ibv_device_ops
	node_type	int32
	transport_type	int32
	name		[64]_Ctype_char
	dev_name	[64]_Ctype_char
	dev_path	[256]_Ctype_char
	ibdev_path	[256]_Ctype_char
}

type _Ctype_struct_ibv_global_route struct {
	dgid		[16]byte
	flow_label	_Ctype_uint32_t
	sgid_index	_Ctype_uint8_t
	hop_limit	_Ctype_uint8_t
	traffic_class	_Ctype_uint8_t
	_		[1]byte
}

type _Ctype_struct_ibv_mr struct {
	context	*_Ctype_struct_ibv_context
	pd	*_Ctype_struct_ibv_pd
	addr	unsafe.Pointer
	length	_Ctype_size_t
	handle	_Ctype_uint32_t
	lkey	_Ctype_uint32_t
	rkey	_Ctype_uint32_t
	_	[4]byte
}

type _Ctype_struct_ibv_pd struct {
	context	*_Ctype_struct_ibv_context
	handle	_Ctype_uint32_t
	_	[4]byte
}

type _Ctype_struct_ibv_qp struct {
	context			*_Ctype_struct_ibv_context
	qp_context		unsafe.Pointer
	pd			*_Ctype_struct_ibv_pd
	send_cq			*_Ctype_struct_ibv_cq
	recv_cq			*_Ctype_struct_ibv_cq
	srq			*_Ctype_struct_ibv_srq
	handle			_Ctype_uint32_t
	qp_num			_Ctype_uint32_t
	state			uint32
	qp_type			uint32
	mutex			_Ctype_pthread_mutex_t
	cond			_Ctype_pthread_cond_t
	events_completed	_Ctype_uint32_t
	_			[4]byte
}

type _Ctype_struct_ibv_qp_attr struct {
	qp_state		uint32
	cur_qp_state		uint32
	path_mtu		uint32
	path_mig_state		uint32
	qkey			_Ctype_uint32_t
	rq_psn			_Ctype_uint32_t
	sq_psn			_Ctype_uint32_t
	dest_qp_num		_Ctype_uint32_t
	qp_access_flags		_Ctype_uint
	cap			_Ctype_struct_ibv_qp_cap
	ah_attr			_Ctype_struct_ibv_ah_attr
	alt_ah_attr		_Ctype_struct_ibv_ah_attr
	pkey_index		_Ctype_uint16_t
	alt_pkey_index		_Ctype_uint16_t
	en_sqd_async_notify	_Ctype_uint8_t
	sq_draining		_Ctype_uint8_t
	max_rd_atomic		_Ctype_uint8_t
	max_dest_rd_atomic	_Ctype_uint8_t
	min_rnr_timer		_Ctype_uint8_t
	port_num		_Ctype_uint8_t
	timeout			_Ctype_uint8_t
	retry_cnt		_Ctype_uint8_t
	rnr_retry		_Ctype_uint8_t
	alt_port_num		_Ctype_uint8_t
	alt_timeout		_Ctype_uint8_t
	rate_limit		_Ctype_uint32_t
	_			[4]byte
}

type _Ctype_struct_ibv_qp_cap struct {
	max_send_wr	_Ctype_uint32_t
	max_recv_wr	_Ctype_uint32_t
	max_send_sge	_Ctype_uint32_t
	max_recv_sge	_Ctype_uint32_t
	max_inline_data	_Ctype_uint32_t
}

type _Ctype_struct_ibv_qp_init_attr struct {
	qp_context	unsafe.Pointer
	send_cq		*_Ctype_struct_ibv_cq
	recv_cq		*_Ctype_struct_ibv_cq
	srq		*_Ctype_struct_ibv_srq
	cap		_Ctype_struct_ibv_qp_cap
	qp_type		uint32
	sq_sig_all	_Ctype_int
	_		[4]byte
}

type _Ctype_struct_ibv_recv_wr struct {
	wr_id	_Ctype_uint64_t
	next	*_Ctype_struct_ibv_recv_wr
	sg_list	*_Ctype_struct_ibv_sge
	num_sge	_Ctype_int
	_	[4]byte
}

type _Ctype_struct_ibv_sa_path_rec struct {
	dgid				[16]byte
	sgid				[16]byte
	dlid				_Ctype___be16
	slid				_Ctype___be16
	raw_traffic			_Ctype_int
	flow_label			_Ctype___be32
	hop_limit			_Ctype_uint8_t
	traffic_class			_Ctype_uint8_t
	reversible			_Ctype_int
	numb_path			_Ctype_uint8_t
	pkey				_Ctype___be16
	sl				_Ctype_uint8_t
	mtu_selector			_Ctype_uint8_t
	mtu				_Ctype_uint8_t
	rate_selector			_Ctype_uint8_t
	rate				_Ctype_uint8_t
	packet_life_time_selector	_Ctype_uint8_t
	packet_life_time		_Ctype_uint8_t
	preference			_Ctype_uint8_t
}

type _Ctype_struct_ibv_send_wr struct {
	wr_id		_Ctype_uint64_t
	next		*_Ctype_struct_ibv_send_wr
	sg_list		*_Ctype_struct_ibv_sge
	num_sge		_Ctype_int
	opcode		uint32
	send_flags	_Ctype_uint
	anon0		[4]byte
	wr		[32]byte
	qp_type		[4]byte
	_		[4]byte
	anon1		[48]byte
}

type _Ctype_struct_ibv_sge struct {
	addr	_Ctype_uint64_t
	length	_Ctype_uint32_t
	lkey	_Ctype_uint32_t
}

type _Ctype_struct_ibv_srq struct {
	context			*_Ctype_struct_ibv_context
	srq_context		unsafe.Pointer
	pd			*_Ctype_struct_ibv_pd
	handle			_Ctype_uint32_t
	_			[4]byte
	mutex			_Ctype_pthread_mutex_t
	cond			_Ctype_pthread_cond_t
	events_completed	_Ctype_uint32_t
	_			[4]byte
}

type _Ctype_struct_ibv_wc struct {
	wr_id		_Ctype_uint64_t
	status		uint32
	opcode		uint32
	vendor_err	_Ctype_uint32_t
	byte_len	_Ctype_uint32_t
	anon0		[4]byte
	qp_num		_Ctype_uint32_t
	src_qp		_Ctype_uint32_t
	wc_flags	_Ctype_uint
	pkey_index	_Ctype_uint16_t
	slid		_Ctype_uint16_t
	sl		_Ctype_uint8_t
	dlid_path_bits	_Ctype_uint8_t
	_		[2]byte
}

type _Ctype_struct_in6_addr struct {
	__in6_u [16]byte
}

type _Ctype_struct_in_addr struct {
	s_addr _Ctype_in_addr_t
}

type _Ctype_struct_pollfd struct {
	fd	_Ctype_int
	events	_Ctype_short
	revents	_Ctype_short
}

type _Ctype_struct_rdma_addr struct {
	anon0	[128]byte
	anon1	[128]byte
	addr	[40]byte
}

type _Ctype_struct_rdma_cm_event struct {
	id		*_Ctype_struct_rdma_cm_id
	listen_id	*_Ctype_struct_rdma_cm_id
	event		uint32
	status		_Ctype_int
	param		[56]byte
}

type _Ctype_struct_rdma_cm_id struct {
	verbs		*_Ctype_struct_ibv_context
	channel		*_Ctype_struct_rdma_event_channel
	context		unsafe.Pointer
	qp		*_Ctype_struct_ibv_qp
	route		_Ctype_struct_rdma_route
	ps		uint32
	port_num	_Ctype_uint8_t
	event		*_Ctype_struct_rdma_cm_event
	send_cq_channel	*_Ctype_struct_ibv_comp_channel
	send_cq		*_Ctype_struct_ibv_cq
	recv_cq_channel	*_Ctype_struct_ibv_comp_channel
	recv_cq		*_Ctype_struct_ibv_cq
	srq		*_Ctype_struct_ibv_srq
	pd		*_Ctype_struct_ibv_pd
	qp_type		uint32
	_		[4]byte
}

type _Ctype_struct_rdma_conn_param struct {
	private_data		unsafe.Pointer
	private_data_len	_Ctype_uint8_t
	responder_resources	_Ctype_uint8_t
	initiator_depth		_Ctype_uint8_t
	flow_control		_Ctype_uint8_t
	retry_count		_Ctype_uint8_t
	rnr_retry_count		_Ctype_uint8_t
	srq			_Ctype_uint8_t
	qp_num			_Ctype_uint32_t
	_			[4]byte
}

type _Ctype_struct_rdma_event_channel struct {
	fd _Ctype_int
}

type _Ctype_struct_rdma_route struct {
	addr		_Ctype_struct_rdma_addr
	path_rec	*_Ctype_struct_ibv_sa_path_rec
	num_paths	_Ctype_int
	_		[4]byte
}

type _Ctype_struct_rping_rdma_info struct {
	buf	_Ctype_uint64_t
	rkey	_Ctype_uint32_t
	size	_Ctype_uint32_t
}

type _Ctype_struct_sockaddr struct {
	sa_family	_Ctype_sa_family_t
	sa_data		[14]_Ctype_char
}

type _Ctype_struct_sockaddr_in struct {
	sin_family	_Ctype_sa_family_t
	sin_port	_Ctype_in_port_t
	sin_addr	_Ctype_struct_in_addr
	sin_zero	[8]_Ctype_uchar
}

type _Ctype_struct_sockaddr_in6 struct {
	sin6_family	_Ctype_sa_family_t
	sin6_port	_Ctype_in_port_t
	sin6_flowinfo	_Ctype_uint32_t
	sin6_addr	_Ctype_struct_in6_addr
	sin6_scope_id	_Ctype_uint32_t
}

type _Ctype_struct_sockaddr_storage struct {
	ss_family	_Ctype_sa_family_t
	__ss_padding	[118]_Ctype_char
	__ss_align	_Ctype_ulong
}

type _Ctype_uchar uint8

type _Ctype_uint uint32

type _Ctype_uint16_t = _Ctype___uint16_t

type _Ctype_uint32_t = _Ctype___uint32_t

type _Ctype_uint64_t = _Ctype___uint64_t

type _Ctype_uint8_t = _Ctype___uint8_t

type _Ctype_ulong uint64

type _Ctype_ulonglong uint64

type _Ctype_union___0 = [40]byte

type _Ctype_union___1 = [48]byte

type _Ctype_union___10 = [40]byte

type _Ctype_union___11 = [16]byte

type _Ctype_union___12 = [8]byte

type _Ctype_union___2 = [4]byte

type _Ctype_union___3 = [32]byte

type _Ctype_union___4 = [4]byte

type _Ctype_union___5 = [48]byte

type _Ctype_union___6 = [4]byte

type _Ctype_union___7 = [56]byte

type _Ctype_union___8 = [128]byte

type _Ctype_union___9 = [128]byte

type _Ctype_union_ibv_gid = [16]byte

type _Ctype_ushort uint16

type _Ctype_void [0]byte

//go:linkname _cgo_runtime_cgocall runtime.cgocall
func _cgo_runtime_cgocall(unsafe.Pointer, uintptr) int32

//go:linkname _cgoCheckPointer runtime.cgoCheckPointer
//go:noescape
func _cgoCheckPointer(interface{}, interface{})

//go:linkname _cgoCheckResult runtime.cgoCheckResult
//go:noescape
func _cgoCheckResult(interface{})
const _Ciconst_AF_INET = 0x2
const _Ciconst_AF_INET6 = 0xa
const _Ciconst_EFD_NONBLOCK = 0x800
const _Ciconst_IBV_ACCESS_LOCAL_WRITE = 0x1
const _Ciconst_IBV_ACCESS_REMOTE_READ = 0x4
const _Ciconst_IBV_ACCESS_REMOTE_WRITE = 0x2
const _Ciconst_IBV_QPS_ERR = 0x6
const _Ciconst_IBV_QPS_INIT = 0x1
const _Ciconst_IBV_QPT_RC = 0x2
const _Ciconst_IBV_QP_ACCESS_FLAGS = 0x8
const _Ciconst_IBV_QP_PKEY_INDEX = 0x10
const _Ciconst_IBV_QP_PORT = 0x20
const _Ciconst_IBV_QP_STATE = 0x1
const _Ciconst_IBV_WC_RDMA_READ = 0x2
const _Ciconst_IBV_WC_RDMA_WRITE = 0x1
const _Ciconst_IBV_WC_RECV = 0x80
const _Ciconst_IBV_WC_SEND = 0x0
const _Ciconst_IBV_WC_WR_FLUSH_ERR = 0x5
const _Ciconst_INET6_ADDRSTRLEN = 0x2e
const _Ciconst_PF_INET = 0x2
const _Ciconst_POLLIN = 0x1
const _Ciconst_RDMA_CM_EVENT_ADDR_ERROR = 0x1
const _Ciconst_RDMA_CM_EVENT_ADDR_RESOLVED = 0x0
const _Ciconst_RDMA_CM_EVENT_CONNECT_ERROR = 0x6
const _Ciconst_RDMA_CM_EVENT_CONNECT_REQUEST = 0x4
const _Ciconst_RDMA_CM_EVENT_CONNECT_RESPONSE = 0x5
const _Ciconst_RDMA_CM_EVENT_DEVICE_REMOVAL = 0xb
const _Ciconst_RDMA_CM_EVENT_DISCONNECTED = 0xa
const _Ciconst_RDMA_CM_EVENT_ESTABLISHED = 0x9
const _Ciconst_RDMA_CM_EVENT_REJECTED = 0x8
const _Ciconst_RDMA_CM_EVENT_ROUTE_ERROR = 0x3
const _Ciconst_RDMA_CM_EVENT_ROUTE_RESOLVED = 0x2
const _Ciconst_RDMA_CM_EVENT_UNREACHABLE = 0x7
const _Ciconst_RDMA_PS_TCP = 0x106
const _Ciconst_sizeof_struct_ibv_qp_attr = 0x90
const _Ciconst_sizeof_struct_ibv_qp_init_attr = 0x40
const _Ciconst_sizeof_struct_rping_rdma_info = 0x10
const _Ciconst_sizeof_struct_sockaddr_storage = 0x80
const _Ciconst_sizeof_uint64_t = 0x8


// CString converts the Go string s to a C string.
//
// The C string is allocated in the C heap using malloc.
// It is the caller's responsibility to arrange for it to be
// freed, such as by calling C.free (be sure to include stdlib.h
// if C.free is needed).
func _Cfunc_CString(s string) *_Ctype_char {
	if len(s)+1 <= 0 {
		panic("string too large")
	}
	p := _cgo_cmalloc(uint64(len(s)+1))
	sliceHeader := struct {
		p   unsafe.Pointer
		len int
		cap int
	}{p, len(s)+1, len(s)+1}
	b := *(*[]byte)(unsafe.Pointer(&sliceHeader))
	copy(b, s)
	b[len(s)] = 0
	return (*_Ctype_char)(p)
}

//go:linkname _cgo_runtime_gobytes runtime.gobytes
func _cgo_runtime_gobytes(unsafe.Pointer, int) []byte

// GoBytes converts the C data p with explicit length l to a Go []byte.
func _Cfunc_GoBytes(p unsafe.Pointer, l _Ctype_int) []byte {
	return _cgo_runtime_gobytes(p, int(l))
}

//go:linkname _cgo_runtime_gostring runtime.gostring
func _cgo_runtime_gostring(*_Ctype_char) string

// GoString converts the C string p into a Go string.
func _Cfunc_GoString(p *_Ctype_char) string {
	return _cgo_runtime_gostring(p)
}

//go:linkname _cgo_runtime_gostringn runtime.gostringn
func _cgo_runtime_gostringn(*_Ctype_char, int) string

// GoStringN converts the C data p with explicit length l to a Go string.
func _Cfunc_GoStringN(p *_Ctype_char, l _Ctype_int) string {
	return _cgo_runtime_gostringn(p, int(l))
}
//go:cgo_import_static _cgo_f4c9d554b24c_Cfunc_alloc_pd_wrapper
//go:linkname __cgofn__cgo_f4c9d554b24c_Cfunc_alloc_pd_wrapper _cgo_f4c9d554b24c_Cfunc_alloc_pd_wrapper
var __cgofn__cgo_f4c9d554b24c_Cfunc_alloc_pd_wrapper byte
var _cgo_f4c9d554b24c_Cfunc_alloc_pd_wrapper = unsafe.Pointer(&__cgofn__cgo_f4c9d554b24c_Cfunc_alloc_pd_wrapper)

//go:cgo_unsafe_args
func _Cfunc_alloc_pd_wrapper(p0 *_Ctype_struct_ibv_context, p1 **_Ctype_struct_ibv_pd) (r1 _Ctype_int) {
	_cgo_runtime_cgocall(_cgo_f4c9d554b24c_Cfunc_alloc_pd_wrapper, uintptr(unsafe.Pointer(&p0)))
	if _Cgo_always_false {
		_Cgo_use(p0)
		_Cgo_use(p1)
	}
	return
}
//go:cgo_import_static _cgo_f4c9d554b24c_Cfunc_close
//go:linkname __cgofn__cgo_f4c9d554b24c_Cfunc_close _cgo_f4c9d554b24c_Cfunc_close
var __cgofn__cgo_f4c9d554b24c_Cfunc_close byte
var _cgo_f4c9d554b24c_Cfunc_close = unsafe.Pointer(&__cgofn__cgo_f4c9d554b24c_Cfunc_close)

//go:cgo_unsafe_args
func _Cfunc_close(p0 _Ctype_int) (r1 _Ctype_int) {
	_cgo_runtime_cgocall(_cgo_f4c9d554b24c_Cfunc_close, uintptr(unsafe.Pointer(&p0)))
	if _Cgo_always_false {
		_Cgo_use(p0)
	}
	return
}
//go:cgo_import_static _cgo_f4c9d554b24c_Cfunc_create_comp_channel_wrapper
//go:linkname __cgofn__cgo_f4c9d554b24c_Cfunc_create_comp_channel_wrapper _cgo_f4c9d554b24c_Cfunc_create_comp_channel_wrapper
var __cgofn__cgo_f4c9d554b24c_Cfunc_create_comp_channel_wrapper byte
var _cgo_f4c9d554b24c_Cfunc_create_comp_channel_wrapper = unsafe.Pointer(&__cgofn__cgo_f4c9d554b24c_Cfunc_create_comp_channel_wrapper)

//go:cgo_unsafe_args
func _Cfunc_create_comp_channel_wrapper(p0 *_Ctype_struct_ibv_context, p1 **_Ctype_struct_ibv_comp_channel) (r1 _Ctype_int) {
	_cgo_runtime_cgocall(_cgo_f4c9d554b24c_Cfunc_create_comp_channel_wrapper, uintptr(unsafe.Pointer(&p0)))
	if _Cgo_always_false {
		_Cgo_use(p0)
		_Cgo_use(p1)
	}
	return
}
//go:cgo_import_static _cgo_f4c9d554b24c_Cfunc_create_cq_wrapper
//go:linkname __cgofn__cgo_f4c9d554b24c_Cfunc_create_cq_wrapper _cgo_f4c9d554b24c_Cfunc_create_cq_wrapper
var __cgofn__cgo_f4c9d554b24c_Cfunc_create_cq_wrapper byte
var _cgo_f4c9d554b24c_Cfunc_create_cq_wrapper = unsafe.Pointer(&__cgofn__cgo_f4c9d554b24c_Cfunc_create_cq_wrapper)

//go:cgo_unsafe_args
func _Cfunc_create_cq_wrapper(p0 *_Ctype_struct_ibv_context, p1 _Ctype_int, p2 *_Ctype_struct_ibv_comp_channel, p3 **_Ctype_struct_ibv_cq) (r1 _Ctype_int) {
	_cgo_runtime_cgocall(_cgo_f4c9d554b24c_Cfunc_create_cq_wrapper, uintptr(unsafe.Pointer(&p0)))
	if _Cgo_always_false {
		_Cgo_use(p0)
		_Cgo_use(p1)
		_Cgo_use(p2)
		_Cgo_use(p3)
	}
	return
}
//go:cgo_import_static _cgo_f4c9d554b24c_Cfunc_create_event_channel_wrapper
//go:linkname __cgofn__cgo_f4c9d554b24c_Cfunc_create_event_channel_wrapper _cgo_f4c9d554b24c_Cfunc_create_event_channel_wrapper
var __cgofn__cgo_f4c9d554b24c_Cfunc_create_event_channel_wrapper byte
var _cgo_f4c9d554b24c_Cfunc_create_event_channel_wrapper = unsafe.Pointer(&__cgofn__cgo_f4c9d554b24c_Cfunc_create_event_channel_wrapper)

//go:cgo_unsafe_args
func _Cfunc_create_event_channel_wrapper(p0 **_Ctype_struct_rdma_event_channel) (r1 _Ctype_int) {
	_cgo_runtime_cgocall(_cgo_f4c9d554b24c_Cfunc_create_event_channel_wrapper, uintptr(unsafe.Pointer(&p0)))
	if _Cgo_always_false {
		_Cgo_use(p0)
	}
	return
}
//go:cgo_import_static _cgo_f4c9d554b24c_Cfunc_create_qp_wrapper
//go:linkname __cgofn__cgo_f4c9d554b24c_Cfunc_create_qp_wrapper _cgo_f4c9d554b24c_Cfunc_create_qp_wrapper
var __cgofn__cgo_f4c9d554b24c_Cfunc_create_qp_wrapper byte
var _cgo_f4c9d554b24c_Cfunc_create_qp_wrapper = unsafe.Pointer(&__cgofn__cgo_f4c9d554b24c_Cfunc_create_qp_wrapper)

//go:cgo_unsafe_args
func _Cfunc_create_qp_wrapper(p0 *_Ctype_struct_ibv_pd, p1 *_Ctype_struct_ibv_qp_init_attr, p2 **_Ctype_struct_ibv_qp) (r1 _Ctype_int) {
	_cgo_runtime_cgocall(_cgo_f4c9d554b24c_Cfunc_create_qp_wrapper, uintptr(unsafe.Pointer(&p0)))
	if _Cgo_always_false {
		_Cgo_use(p0)
		_Cgo_use(p1)
		_Cgo_use(p2)
	}
	return
}
//go:cgo_import_static _cgo_f4c9d554b24c_Cfunc_eventfd
//go:linkname __cgofn__cgo_f4c9d554b24c_Cfunc_eventfd _cgo_f4c9d554b24c_Cfunc_eventfd
var __cgofn__cgo_f4c9d554b24c_Cfunc_eventfd byte
var _cgo_f4c9d554b24c_Cfunc_eventfd = unsafe.Pointer(&__cgofn__cgo_f4c9d554b24c_Cfunc_eventfd)

//go:cgo_unsafe_args
func _Cfunc_eventfd(p0 _Ctype_uint, p1 _Ctype_int) (r1 _Ctype_int) {
	_cgo_runtime_cgocall(_cgo_f4c9d554b24c_Cfunc_eventfd, uintptr(unsafe.Pointer(&p0)))
	if _Cgo_always_false {
		_Cgo_use(p0)
		_Cgo_use(p1)
	}
	return
}
//go:cgo_import_static _cgo_f4c9d554b24c_Cfunc_fill_rdma_info
//go:linkname __cgofn__cgo_f4c9d554b24c_Cfunc_fill_rdma_info _cgo_f4c9d554b24c_Cfunc_fill_rdma_info
var __cgofn__cgo_f4c9d554b24c_Cfunc_fill_rdma_info byte
var _cgo_f4c9d554b24c_Cfunc_fill_rdma_info = unsafe.Pointer(&__cgofn__cgo_f4c9d554b24c_Cfunc_fill_rdma_info)

//go:cgo_unsafe_args
func _Cfunc_fill_rdma_info(p0 *_Ctype_struct_rping_rdma_info, p1 _Ctype_uint64_t, p2 _Ctype_uint32_t, p3 _Ctype_uint32_t) (r1 _Ctype_void) {
	_cgo_runtime_cgocall(_cgo_f4c9d554b24c_Cfunc_fill_rdma_info, uintptr(unsafe.Pointer(&p0)))
	if _Cgo_always_false {
		_Cgo_use(p0)
		_Cgo_use(p1)
		_Cgo_use(p2)
		_Cgo_use(p3)
	}
	return
}
//go:cgo_import_static _cgo_f4c9d554b24c_Cfunc_free
//go:linkname __cgofn__cgo_f4c9d554b24c_Cfunc_free _cgo_f4c9d554b24c_Cfunc_free
var __cgofn__cgo_f4c9d554b24c_Cfunc_free byte
var _cgo_f4c9d554b24c_Cfunc_free = unsafe.Pointer(&__cgofn__cgo_f4c9d554b24c_Cfunc_free)

//go:cgo_unsafe_args
func _Cfunc_free(p0 unsafe.Pointer) (r1 _Ctype_void) {
	_cgo_runtime_cgocall(_cgo_f4c9d554b24c_Cfunc_free, uintptr(unsafe.Pointer(&p0)))
	if _Cgo_always_false {
		_Cgo_use(p0)
	}
	return
}
//go:cgo_import_static _cgo_f4c9d554b24c_Cfunc_get_channel_fd
//go:linkname __cgofn__cgo_f4c9d554b24c_Cfunc_get_channel_fd _cgo_f4c9d554b24c_Cfunc_get_channel_fd
var __cgofn__cgo_f4c9d554b24c_Cfunc_get_channel_fd byte
var _cgo_f4c9d554b24c_Cfunc_get_channel_fd = unsafe.Pointer(&__cgofn__cgo_f4c9d554b24c_Cfunc_get_channel_fd)

//go:cgo_unsafe_args
func _Cfunc_get_channel_fd(p0 *_Ctype_struct_rdma_event_channel) (r1 _Ctype_int) {
	_cgo_runtime_cgocall(_cgo_f4c9d554b24c_Cfunc_get_channel_fd, uintptr(unsafe.Pointer(&p0)))
	if _Cgo_always_false {
		_Cgo_use(p0)
	}
	return
}
//go:cgo_import_static _cgo_f4c9d554b24c_Cfunc_get_cm_event_wrapper
//go:linkname __cgofn__cgo_f4c9d554b24c_Cfunc_get_cm_event_wrapper _cgo_f4c9d554b24c_Cfunc_get_cm_event_wrapper
var __cgofn__cgo_f4c9d554b24c_Cfunc_get_cm_event_wrapper byte
var _cgo_f4c9d554b24c_Cfunc_get_cm_event_wrapper = unsafe.Pointer(&__cgofn__cgo_f4c9d554b24c_Cfunc_get_cm_event_wrapper)

//go:cgo_unsafe_args
func _Cfunc_get_cm_event_wrapper(p0 *_Ctype_struct_rdma_event_channel, p1 **_Ctype_struct_rdma_cm_event) (r1 _Ctype_int) {
	_cgo_runtime_cgocall(_cgo_f4c9d554b24c_Cfunc_get_cm_event_wrapper, uintptr(unsafe.Pointer(&p0)))
	if _Cgo_always_false {
		_Cgo_use(p0)
		_Cgo_use(p1)
	}
	return
}
//go:cgo_import_static _cgo_f4c9d554b24c_Cfunc_get_cm_id_qp
//go:linkname __cgofn__cgo_f4c9d554b24c_Cfunc_get_cm_id_qp _cgo_f4c9d554b24c_Cfunc_get_cm_id_qp
var __cgofn__cgo_f4c9d554b24c_Cfunc_get_cm_id_qp byte
var _cgo_f4c9d554b24c_Cfunc_get_cm_id_qp = unsafe.Pointer(&__cgofn__cgo_f4c9d554b24c_Cfunc_get_cm_id_qp)

//go:cgo_unsafe_args
func _Cfunc_get_cm_id_qp(p0 *_Ctype_struct_rdma_cm_id) (r1 *_Ctype_struct_ibv_qp) {
	_cgo_runtime_cgocall(_cgo_f4c9d554b24c_Cfunc_get_cm_id_qp, uintptr(unsafe.Pointer(&p0)))
	if _Cgo_always_false {
		_Cgo_use(p0)
	}
	return
}
//go:cgo_import_static _cgo_f4c9d554b24c_Cfunc_get_cq_event_wrapper
//go:linkname __cgofn__cgo_f4c9d554b24c_Cfunc_get_cq_event_wrapper _cgo_f4c9d554b24c_Cfunc_get_cq_event_wrapper
var __cgofn__cgo_f4c9d554b24c_Cfunc_get_cq_event_wrapper byte
var _cgo_f4c9d554b24c_Cfunc_get_cq_event_wrapper = unsafe.Pointer(&__cgofn__cgo_f4c9d554b24c_Cfunc_get_cq_event_wrapper)

//go:cgo_unsafe_args
func _Cfunc_get_cq_event_wrapper(p0 *_Ctype_struct_ibv_comp_channel, p1 **_Ctype_struct_ibv_cq, p2 *unsafe.Pointer) (r1 _Ctype_int) {
	_cgo_runtime_cgocall(_cgo_f4c9d554b24c_Cfunc_get_cq_event_wrapper, uintptr(unsafe.Pointer(&p0)))
	if _Cgo_always_false {
		_Cgo_use(p0)
		_Cgo_use(p1)
		_Cgo_use(p2)
	}
	return
}
//go:cgo_import_static _cgo_f4c9d554b24c_Cfunc_get_event_event
//go:linkname __cgofn__cgo_f4c9d554b24c_Cfunc_get_event_event _cgo_f4c9d554b24c_Cfunc_get_event_event
var __cgofn__cgo_f4c9d554b24c_Cfunc_get_event_event byte
var _cgo_f4c9d554b24c_Cfunc_get_event_event = unsafe.Pointer(&__cgofn__cgo_f4c9d554b24c_Cfunc_get_event_event)

//go:cgo_unsafe_args
func _Cfunc_get_event_event(p0 *_Ctype_struct_rdma_cm_event) (r1 _Ctype_int) {
	_cgo_runtime_cgocall(_cgo_f4c9d554b24c_Cfunc_get_event_event, uintptr(unsafe.Pointer(&p0)))
	if _Cgo_always_false {
		_Cgo_use(p0)
	}
	return
}
//go:cgo_import_static _cgo_f4c9d554b24c_Cfunc_get_event_id
//go:linkname __cgofn__cgo_f4c9d554b24c_Cfunc_get_event_id _cgo_f4c9d554b24c_Cfunc_get_event_id
var __cgofn__cgo_f4c9d554b24c_Cfunc_get_event_id byte
var _cgo_f4c9d554b24c_Cfunc_get_event_id = unsafe.Pointer(&__cgofn__cgo_f4c9d554b24c_Cfunc_get_event_id)

//go:cgo_unsafe_args
func _Cfunc_get_event_id(p0 *_Ctype_struct_rdma_cm_event) (r1 *_Ctype_struct_rdma_cm_id) {
	_cgo_runtime_cgocall(_cgo_f4c9d554b24c_Cfunc_get_event_id, uintptr(unsafe.Pointer(&p0)))
	if _Cgo_always_false {
		_Cgo_use(p0)
	}
	return
}
//go:cgo_import_static _cgo_f4c9d554b24c_Cfunc_get_event_status
//go:linkname __cgofn__cgo_f4c9d554b24c_Cfunc_get_event_status _cgo_f4c9d554b24c_Cfunc_get_event_status
var __cgofn__cgo_f4c9d554b24c_Cfunc_get_event_status byte
var _cgo_f4c9d554b24c_Cfunc_get_event_status = unsafe.Pointer(&__cgofn__cgo_f4c9d554b24c_Cfunc_get_event_status)

//go:cgo_unsafe_args
func _Cfunc_get_event_status(p0 *_Ctype_struct_rdma_cm_event) (r1 _Ctype_int) {
	_cgo_runtime_cgocall(_cgo_f4c9d554b24c_Cfunc_get_event_status, uintptr(unsafe.Pointer(&p0)))
	if _Cgo_always_false {
		_Cgo_use(p0)
	}
	return
}
//go:cgo_import_static _cgo_f4c9d554b24c_Cfunc_get_lkey
//go:linkname __cgofn__cgo_f4c9d554b24c_Cfunc_get_lkey _cgo_f4c9d554b24c_Cfunc_get_lkey
var __cgofn__cgo_f4c9d554b24c_Cfunc_get_lkey byte
var _cgo_f4c9d554b24c_Cfunc_get_lkey = unsafe.Pointer(&__cgofn__cgo_f4c9d554b24c_Cfunc_get_lkey)

//go:cgo_unsafe_args
func _Cfunc_get_lkey(p0 *_Ctype_struct_ibv_mr) (r1 _Ctype_uint32_t) {
	_cgo_runtime_cgocall(_cgo_f4c9d554b24c_Cfunc_get_lkey, uintptr(unsafe.Pointer(&p0)))
	if _Cgo_always_false {
		_Cgo_use(p0)
	}
	return
}
//go:cgo_import_static _cgo_f4c9d554b24c_Cfunc_get_port_num
//go:linkname __cgofn__cgo_f4c9d554b24c_Cfunc_get_port_num _cgo_f4c9d554b24c_Cfunc_get_port_num
var __cgofn__cgo_f4c9d554b24c_Cfunc_get_port_num byte
var _cgo_f4c9d554b24c_Cfunc_get_port_num = unsafe.Pointer(&__cgofn__cgo_f4c9d554b24c_Cfunc_get_port_num)

//go:cgo_unsafe_args
func _Cfunc_get_port_num(p0 *_Ctype_struct_rdma_cm_id) (r1 _Ctype_uint8_t) {
	_cgo_runtime_cgocall(_cgo_f4c9d554b24c_Cfunc_get_port_num, uintptr(unsafe.Pointer(&p0)))
	if _Cgo_always_false {
		_Cgo_use(p0)
	}
	return
}
//go:cgo_import_static _cgo_f4c9d554b24c_Cfunc_get_qp_num
//go:linkname __cgofn__cgo_f4c9d554b24c_Cfunc_get_qp_num _cgo_f4c9d554b24c_Cfunc_get_qp_num
var __cgofn__cgo_f4c9d554b24c_Cfunc_get_qp_num byte
var _cgo_f4c9d554b24c_Cfunc_get_qp_num = unsafe.Pointer(&__cgofn__cgo_f4c9d554b24c_Cfunc_get_qp_num)

//go:cgo_unsafe_args
func _Cfunc_get_qp_num(p0 *_Ctype_struct_ibv_qp) (r1 _Ctype_uint32_t) {
	_cgo_runtime_cgocall(_cgo_f4c9d554b24c_Cfunc_get_qp_num, uintptr(unsafe.Pointer(&p0)))
	if _Cgo_always_false {
		_Cgo_use(p0)
	}
	return
}
//go:cgo_import_static _cgo_f4c9d554b24c_Cfunc_get_rdma_buf_strlen
//go:linkname __cgofn__cgo_f4c9d554b24c_Cfunc_get_rdma_buf_strlen _cgo_f4c9d554b24c_Cfunc_get_rdma_buf_strlen
var __cgofn__cgo_f4c9d554b24c_Cfunc_get_rdma_buf_strlen byte
var _cgo_f4c9d554b24c_Cfunc_get_rdma_buf_strlen = unsafe.Pointer(&__cgofn__cgo_f4c9d554b24c_Cfunc_get_rdma_buf_strlen)

//go:cgo_unsafe_args
func _Cfunc_get_rdma_buf_strlen(p0 *_Ctype_char) (r1 _Ctype_uint32_t) {
	_cgo_runtime_cgocall(_cgo_f4c9d554b24c_Cfunc_get_rdma_buf_strlen, uintptr(unsafe.Pointer(&p0)))
	if _Cgo_always_false {
		_Cgo_use(p0)
	}
	return
}
//go:cgo_import_static _cgo_f4c9d554b24c_Cfunc_get_rkey
//go:linkname __cgofn__cgo_f4c9d554b24c_Cfunc_get_rkey _cgo_f4c9d554b24c_Cfunc_get_rkey
var __cgofn__cgo_f4c9d554b24c_Cfunc_get_rkey byte
var _cgo_f4c9d554b24c_Cfunc_get_rkey = unsafe.Pointer(&__cgofn__cgo_f4c9d554b24c_Cfunc_get_rkey)

//go:cgo_unsafe_args
func _Cfunc_get_rkey(p0 *_Ctype_struct_ibv_mr) (r1 _Ctype_uint32_t) {
	_cgo_runtime_cgocall(_cgo_f4c9d554b24c_Cfunc_get_rkey, uintptr(unsafe.Pointer(&p0)))
	if _Cgo_always_false {
		_Cgo_use(p0)
	}
	return
}
//go:cgo_import_static _cgo_f4c9d554b24c_Cfunc_get_verbs
//go:linkname __cgofn__cgo_f4c9d554b24c_Cfunc_get_verbs _cgo_f4c9d554b24c_Cfunc_get_verbs
var __cgofn__cgo_f4c9d554b24c_Cfunc_get_verbs byte
var _cgo_f4c9d554b24c_Cfunc_get_verbs = unsafe.Pointer(&__cgofn__cgo_f4c9d554b24c_Cfunc_get_verbs)

//go:cgo_unsafe_args
func _Cfunc_get_verbs(p0 *_Ctype_struct_rdma_cm_id) (r1 *_Ctype_struct_ibv_context) {
	_cgo_runtime_cgocall(_cgo_f4c9d554b24c_Cfunc_get_verbs, uintptr(unsafe.Pointer(&p0)))
	if _Cgo_always_false {
		_Cgo_use(p0)
	}
	return
}
//go:cgo_import_static _cgo_f4c9d554b24c_Cfunc_getnameinfo_wrapper
//go:linkname __cgofn__cgo_f4c9d554b24c_Cfunc_getnameinfo_wrapper _cgo_f4c9d554b24c_Cfunc_getnameinfo_wrapper
var __cgofn__cgo_f4c9d554b24c_Cfunc_getnameinfo_wrapper byte
var _cgo_f4c9d554b24c_Cfunc_getnameinfo_wrapper = unsafe.Pointer(&__cgofn__cgo_f4c9d554b24c_Cfunc_getnameinfo_wrapper)

//go:cgo_unsafe_args
func _Cfunc_getnameinfo_wrapper(p0 *_Ctype_struct_sockaddr, p1 _Ctype_socklen_t, p2 *_Ctype_char, p3 _Ctype_socklen_t) (r1 _Ctype_void) {
	_cgo_runtime_cgocall(_cgo_f4c9d554b24c_Cfunc_getnameinfo_wrapper, uintptr(unsafe.Pointer(&p0)))
	if _Cgo_always_false {
		_Cgo_use(p0)
		_Cgo_use(p1)
		_Cgo_use(p2)
		_Cgo_use(p3)
	}
	return
}
//go:cgo_import_static _cgo_f4c9d554b24c_Cfunc_go_be16toh
//go:linkname __cgofn__cgo_f4c9d554b24c_Cfunc_go_be16toh _cgo_f4c9d554b24c_Cfunc_go_be16toh
var __cgofn__cgo_f4c9d554b24c_Cfunc_go_be16toh byte
var _cgo_f4c9d554b24c_Cfunc_go_be16toh = unsafe.Pointer(&__cgofn__cgo_f4c9d554b24c_Cfunc_go_be16toh)

//go:cgo_unsafe_args
func _Cfunc_go_be16toh(p0 _Ctype_uint16_t) (r1 _Ctype_uint16_t) {
	_cgo_runtime_cgocall(_cgo_f4c9d554b24c_Cfunc_go_be16toh, uintptr(unsafe.Pointer(&p0)))
	if _Cgo_always_false {
		_Cgo_use(p0)
	}
	return
}
//go:cgo_import_static _cgo_f4c9d554b24c_Cfunc_go_htobe16
//go:linkname __cgofn__cgo_f4c9d554b24c_Cfunc_go_htobe16 _cgo_f4c9d554b24c_Cfunc_go_htobe16
var __cgofn__cgo_f4c9d554b24c_Cfunc_go_htobe16 byte
var _cgo_f4c9d554b24c_Cfunc_go_htobe16 = unsafe.Pointer(&__cgofn__cgo_f4c9d554b24c_Cfunc_go_htobe16)

//go:cgo_unsafe_args
func _Cfunc_go_htobe16(p0 _Ctype_uint16_t) (r1 _Ctype_uint16_t) {
	_cgo_runtime_cgocall(_cgo_f4c9d554b24c_Cfunc_go_htobe16, uintptr(unsafe.Pointer(&p0)))
	if _Cgo_always_false {
		_Cgo_use(p0)
	}
	return
}
//go:cgo_import_static _cgo_f4c9d554b24c_Cfunc_ibv_ack_cq_events
//go:linkname __cgofn__cgo_f4c9d554b24c_Cfunc_ibv_ack_cq_events _cgo_f4c9d554b24c_Cfunc_ibv_ack_cq_events
var __cgofn__cgo_f4c9d554b24c_Cfunc_ibv_ack_cq_events byte
var _cgo_f4c9d554b24c_Cfunc_ibv_ack_cq_events = unsafe.Pointer(&__cgofn__cgo_f4c9d554b24c_Cfunc_ibv_ack_cq_events)

//go:cgo_unsafe_args
func _Cfunc_ibv_ack_cq_events(p0 *_Ctype_struct_ibv_cq, p1 _Ctype_uint) (r1 _Ctype_void) {
	_cgo_runtime_cgocall(_cgo_f4c9d554b24c_Cfunc_ibv_ack_cq_events, uintptr(unsafe.Pointer(&p0)))
	if _Cgo_always_false {
		_Cgo_use(p0)
		_Cgo_use(p1)
	}
	return
}
//go:cgo_import_static _cgo_f4c9d554b24c_Cfunc_ibv_dealloc_pd
//go:linkname __cgofn__cgo_f4c9d554b24c_Cfunc_ibv_dealloc_pd _cgo_f4c9d554b24c_Cfunc_ibv_dealloc_pd
var __cgofn__cgo_f4c9d554b24c_Cfunc_ibv_dealloc_pd byte
var _cgo_f4c9d554b24c_Cfunc_ibv_dealloc_pd = unsafe.Pointer(&__cgofn__cgo_f4c9d554b24c_Cfunc_ibv_dealloc_pd)

//go:cgo_unsafe_args
func _Cfunc_ibv_dealloc_pd(p0 *_Ctype_struct_ibv_pd) (r1 _Ctype_int) {
	_cgo_runtime_cgocall(_cgo_f4c9d554b24c_Cfunc_ibv_dealloc_pd, uintptr(unsafe.Pointer(&p0)))
	if _Cgo_always_false {
		_Cgo_use(p0)
	}
	return
}
//go:cgo_import_static _cgo_f4c9d554b24c_Cfunc_ibv_dereg_mr
//go:linkname __cgofn__cgo_f4c9d554b24c_Cfunc_ibv_dereg_mr _cgo_f4c9d554b24c_Cfunc_ibv_dereg_mr
var __cgofn__cgo_f4c9d554b24c_Cfunc_ibv_dereg_mr byte
var _cgo_f4c9d554b24c_Cfunc_ibv_dereg_mr = unsafe.Pointer(&__cgofn__cgo_f4c9d554b24c_Cfunc_ibv_dereg_mr)

//go:cgo_unsafe_args
func _Cfunc_ibv_dereg_mr(p0 *_Ctype_struct_ibv_mr) (r1 _Ctype_int) {
	_cgo_runtime_cgocall(_cgo_f4c9d554b24c_Cfunc_ibv_dereg_mr, uintptr(unsafe.Pointer(&p0)))
	if _Cgo_always_false {
		_Cgo_use(p0)
	}
	return
}
//go:cgo_import_static _cgo_f4c9d554b24c_Cfunc_ibv_destroy_comp_channel
//go:linkname __cgofn__cgo_f4c9d554b24c_Cfunc_ibv_destroy_comp_channel _cgo_f4c9d554b24c_Cfunc_ibv_destroy_comp_channel
var __cgofn__cgo_f4c9d554b24c_Cfunc_ibv_destroy_comp_channel byte
var _cgo_f4c9d554b24c_Cfunc_ibv_destroy_comp_channel = unsafe.Pointer(&__cgofn__cgo_f4c9d554b24c_Cfunc_ibv_destroy_comp_channel)

//go:cgo_unsafe_args
func _Cfunc_ibv_destroy_comp_channel(p0 *_Ctype_struct_ibv_comp_channel) (r1 _Ctype_int) {
	_cgo_runtime_cgocall(_cgo_f4c9d554b24c_Cfunc_ibv_destroy_comp_channel, uintptr(unsafe.Pointer(&p0)))
	if _Cgo_always_false {
		_Cgo_use(p0)
	}
	return
}
//go:cgo_import_static _cgo_f4c9d554b24c_Cfunc_ibv_destroy_cq
//go:linkname __cgofn__cgo_f4c9d554b24c_Cfunc_ibv_destroy_cq _cgo_f4c9d554b24c_Cfunc_ibv_destroy_cq
var __cgofn__cgo_f4c9d554b24c_Cfunc_ibv_destroy_cq byte
var _cgo_f4c9d554b24c_Cfunc_ibv_destroy_cq = unsafe.Pointer(&__cgofn__cgo_f4c9d554b24c_Cfunc_ibv_destroy_cq)

//go:cgo_unsafe_args
func _Cfunc_ibv_destroy_cq(p0 *_Ctype_struct_ibv_cq) (r1 _Ctype_int) {
	_cgo_runtime_cgocall(_cgo_f4c9d554b24c_Cfunc_ibv_destroy_cq, uintptr(unsafe.Pointer(&p0)))
	if _Cgo_always_false {
		_Cgo_use(p0)
	}
	return
}
//go:cgo_import_static _cgo_f4c9d554b24c_Cfunc_ibv_destroy_qp
//go:linkname __cgofn__cgo_f4c9d554b24c_Cfunc_ibv_destroy_qp _cgo_f4c9d554b24c_Cfunc_ibv_destroy_qp
var __cgofn__cgo_f4c9d554b24c_Cfunc_ibv_destroy_qp byte
var _cgo_f4c9d554b24c_Cfunc_ibv_destroy_qp = unsafe.Pointer(&__cgofn__cgo_f4c9d554b24c_Cfunc_ibv_destroy_qp)

//go:cgo_unsafe_args
func _Cfunc_ibv_destroy_qp(p0 *_Ctype_struct_ibv_qp) (r1 _Ctype_int) {
	_cgo_runtime_cgocall(_cgo_f4c9d554b24c_Cfunc_ibv_destroy_qp, uintptr(unsafe.Pointer(&p0)))
	if _Cgo_always_false {
		_Cgo_use(p0)
	}
	return
}
//go:cgo_import_static _cgo_f4c9d554b24c_Cfunc_ibv_modify_qp
//go:linkname __cgofn__cgo_f4c9d554b24c_Cfunc_ibv_modify_qp _cgo_f4c9d554b24c_Cfunc_ibv_modify_qp
var __cgofn__cgo_f4c9d554b24c_Cfunc_ibv_modify_qp byte
var _cgo_f4c9d554b24c_Cfunc_ibv_modify_qp = unsafe.Pointer(&__cgofn__cgo_f4c9d554b24c_Cfunc_ibv_modify_qp)

//go:cgo_unsafe_args
func _Cfunc_ibv_modify_qp(p0 *_Ctype_struct_ibv_qp, p1 *_Ctype_struct_ibv_qp_attr, p2 _Ctype_int) (r1 _Ctype_int) {
	_cgo_runtime_cgocall(_cgo_f4c9d554b24c_Cfunc_ibv_modify_qp, uintptr(unsafe.Pointer(&p0)))
	if _Cgo_always_false {
		_Cgo_use(p0)
		_Cgo_use(p1)
		_Cgo_use(p2)
	}
	return
}
//go:cgo_import_static _cgo_f4c9d554b24c_Cfunc_ibv_poll_cq
//go:linkname __cgofn__cgo_f4c9d554b24c_Cfunc_ibv_poll_cq _cgo_f4c9d554b24c_Cfunc_ibv_poll_cq
var __cgofn__cgo_f4c9d554b24c_Cfunc_ibv_poll_cq byte
var _cgo_f4c9d554b24c_Cfunc_ibv_poll_cq = unsafe.Pointer(&__cgofn__cgo_f4c9d554b24c_Cfunc_ibv_poll_cq)

//go:cgo_unsafe_args
func _Cfunc_ibv_poll_cq(p0 *_Ctype_struct_ibv_cq, p1 _Ctype_int, p2 *_Ctype_struct_ibv_wc) (r1 _Ctype_int) {
	_cgo_runtime_cgocall(_cgo_f4c9d554b24c_Cfunc_ibv_poll_cq, uintptr(unsafe.Pointer(&p0)))
	if _Cgo_always_false {
		_Cgo_use(p0)
		_Cgo_use(p1)
		_Cgo_use(p2)
	}
	return
}
//go:cgo_import_static _cgo_f4c9d554b24c_Cfunc_ibv_post_recv
//go:linkname __cgofn__cgo_f4c9d554b24c_Cfunc_ibv_post_recv _cgo_f4c9d554b24c_Cfunc_ibv_post_recv
var __cgofn__cgo_f4c9d554b24c_Cfunc_ibv_post_recv byte
var _cgo_f4c9d554b24c_Cfunc_ibv_post_recv = unsafe.Pointer(&__cgofn__cgo_f4c9d554b24c_Cfunc_ibv_post_recv)

//go:cgo_unsafe_args
func _Cfunc_ibv_post_recv(p0 *_Ctype_struct_ibv_qp, p1 *_Ctype_struct_ibv_recv_wr, p2 **_Ctype_struct_ibv_recv_wr) (r1 _Ctype_int) {
	_cgo_runtime_cgocall(_cgo_f4c9d554b24c_Cfunc_ibv_post_recv, uintptr(unsafe.Pointer(&p0)))
	if _Cgo_always_false {
		_Cgo_use(p0)
		_Cgo_use(p1)
		_Cgo_use(p2)
	}
	return
}
//go:cgo_import_static _cgo_f4c9d554b24c_Cfunc_ibv_post_send
//go:linkname __cgofn__cgo_f4c9d554b24c_Cfunc_ibv_post_send _cgo_f4c9d554b24c_Cfunc_ibv_post_send
var __cgofn__cgo_f4c9d554b24c_Cfunc_ibv_post_send byte
var _cgo_f4c9d554b24c_Cfunc_ibv_post_send = unsafe.Pointer(&__cgofn__cgo_f4c9d554b24c_Cfunc_ibv_post_send)

//go:cgo_unsafe_args
func _Cfunc_ibv_post_send(p0 *_Ctype_struct_ibv_qp, p1 *_Ctype_struct_ibv_send_wr, p2 **_Ctype_struct_ibv_send_wr) (r1 _Ctype_int) {
	_cgo_runtime_cgocall(_cgo_f4c9d554b24c_Cfunc_ibv_post_send, uintptr(unsafe.Pointer(&p0)))
	if _Cgo_always_false {
		_Cgo_use(p0)
		_Cgo_use(p1)
		_Cgo_use(p2)
	}
	return
}
//go:cgo_import_static _cgo_f4c9d554b24c_Cfunc_ibv_req_notify_cq
//go:linkname __cgofn__cgo_f4c9d554b24c_Cfunc_ibv_req_notify_cq _cgo_f4c9d554b24c_Cfunc_ibv_req_notify_cq
var __cgofn__cgo_f4c9d554b24c_Cfunc_ibv_req_notify_cq byte
var _cgo_f4c9d554b24c_Cfunc_ibv_req_notify_cq = unsafe.Pointer(&__cgofn__cgo_f4c9d554b24c_Cfunc_ibv_req_notify_cq)

//go:cgo_unsafe_args
func _Cfunc_ibv_req_notify_cq(p0 *_Ctype_struct_ibv_cq, p1 _Ctype_int) (r1 _Ctype_int) {
	_cgo_runtime_cgocall(_cgo_f4c9d554b24c_Cfunc_ibv_req_notify_cq, uintptr(unsafe.Pointer(&p0)))
	if _Cgo_always_false {
		_Cgo_use(p0)
		_Cgo_use(p1)
	}
	return
}
//go:cgo_import_static _cgo_f4c9d554b24c_Cfunc_info_get_buf
//go:linkname __cgofn__cgo_f4c9d554b24c_Cfunc_info_get_buf _cgo_f4c9d554b24c_Cfunc_info_get_buf
var __cgofn__cgo_f4c9d554b24c_Cfunc_info_get_buf byte
var _cgo_f4c9d554b24c_Cfunc_info_get_buf = unsafe.Pointer(&__cgofn__cgo_f4c9d554b24c_Cfunc_info_get_buf)

//go:cgo_unsafe_args
func _Cfunc_info_get_buf(p0 *_Ctype_struct_rping_rdma_info) (r1 _Ctype_uint64_t) {
	_cgo_runtime_cgocall(_cgo_f4c9d554b24c_Cfunc_info_get_buf, uintptr(unsafe.Pointer(&p0)))
	if _Cgo_always_false {
		_Cgo_use(p0)
	}
	return
}
//go:cgo_import_static _cgo_f4c9d554b24c_Cfunc_info_get_rkey
//go:linkname __cgofn__cgo_f4c9d554b24c_Cfunc_info_get_rkey _cgo_f4c9d554b24c_Cfunc_info_get_rkey
var __cgofn__cgo_f4c9d554b24c_Cfunc_info_get_rkey byte
var _cgo_f4c9d554b24c_Cfunc_info_get_rkey = unsafe.Pointer(&__cgofn__cgo_f4c9d554b24c_Cfunc_info_get_rkey)

//go:cgo_unsafe_args
func _Cfunc_info_get_rkey(p0 *_Ctype_struct_rping_rdma_info) (r1 _Ctype_uint32_t) {
	_cgo_runtime_cgocall(_cgo_f4c9d554b24c_Cfunc_info_get_rkey, uintptr(unsafe.Pointer(&p0)))
	if _Cgo_always_false {
		_Cgo_use(p0)
	}
	return
}
//go:cgo_import_static _cgo_f4c9d554b24c_Cfunc_info_get_size
//go:linkname __cgofn__cgo_f4c9d554b24c_Cfunc_info_get_size _cgo_f4c9d554b24c_Cfunc_info_get_size
var __cgofn__cgo_f4c9d554b24c_Cfunc_info_get_size byte
var _cgo_f4c9d554b24c_Cfunc_info_get_size = unsafe.Pointer(&__cgofn__cgo_f4c9d554b24c_Cfunc_info_get_size)

//go:cgo_unsafe_args
func _Cfunc_info_get_size(p0 *_Ctype_struct_rping_rdma_info) (r1 _Ctype_uint32_t) {
	_cgo_runtime_cgocall(_cgo_f4c9d554b24c_Cfunc_info_get_size, uintptr(unsafe.Pointer(&p0)))
	if _Cgo_always_false {
		_Cgo_use(p0)
	}
	return
}
//go:cgo_import_static _cgo_f4c9d554b24c_Cfunc_init_conn_param
//go:linkname __cgofn__cgo_f4c9d554b24c_Cfunc_init_conn_param _cgo_f4c9d554b24c_Cfunc_init_conn_param
var __cgofn__cgo_f4c9d554b24c_Cfunc_init_conn_param byte
var _cgo_f4c9d554b24c_Cfunc_init_conn_param = unsafe.Pointer(&__cgofn__cgo_f4c9d554b24c_Cfunc_init_conn_param)

//go:cgo_unsafe_args
func _Cfunc_init_conn_param(p0 *_Ctype_struct_rdma_conn_param, p1 _Ctype_int, p2 _Ctype_int) (r1 _Ctype_void) {
	_cgo_runtime_cgocall(_cgo_f4c9d554b24c_Cfunc_init_conn_param, uintptr(unsafe.Pointer(&p0)))
	if _Cgo_always_false {
		_Cgo_use(p0)
		_Cgo_use(p1)
		_Cgo_use(p2)
	}
	return
}
//go:cgo_import_static _cgo_f4c9d554b24c_Cfunc_memset
//go:linkname __cgofn__cgo_f4c9d554b24c_Cfunc_memset _cgo_f4c9d554b24c_Cfunc_memset
var __cgofn__cgo_f4c9d554b24c_Cfunc_memset byte
var _cgo_f4c9d554b24c_Cfunc_memset = unsafe.Pointer(&__cgofn__cgo_f4c9d554b24c_Cfunc_memset)

//go:cgo_unsafe_args
func _Cfunc_memset(p0 unsafe.Pointer, p1 _Ctype_int, p2 _Ctype_size_t) (r1 unsafe.Pointer) {
	_cgo_runtime_cgocall(_cgo_f4c9d554b24c_Cfunc_memset, uintptr(unsafe.Pointer(&p0)))
	if _Cgo_always_false {
		_Cgo_use(p0)
		_Cgo_use(p1)
		_Cgo_use(p2)
	}
	return
}
//go:cgo_import_static _cgo_f4c9d554b24c_Cfunc_poll_wrapper
//go:linkname __cgofn__cgo_f4c9d554b24c_Cfunc_poll_wrapper _cgo_f4c9d554b24c_Cfunc_poll_wrapper
var __cgofn__cgo_f4c9d554b24c_Cfunc_poll_wrapper byte
var _cgo_f4c9d554b24c_Cfunc_poll_wrapper = unsafe.Pointer(&__cgofn__cgo_f4c9d554b24c_Cfunc_poll_wrapper)

//go:cgo_unsafe_args
func _Cfunc_poll_wrapper(p0 *_Ctype_struct_pollfd, p1 _Ctype_nfds_t, p2 _Ctype_int) (r1 _Ctype_int) {
	_cgo_runtime_cgocall(_cgo_f4c9d554b24c_Cfunc_poll_wrapper, uintptr(unsafe.Pointer(&p0)))
	if _Cgo_always_false {
		_Cgo_use(p0)
		_Cgo_use(p1)
		_Cgo_use(p2)
	}
	return
}
//go:cgo_import_static _cgo_f4c9d554b24c_Cfunc_rdma_accept
//go:linkname __cgofn__cgo_f4c9d554b24c_Cfunc_rdma_accept _cgo_f4c9d554b24c_Cfunc_rdma_accept
var __cgofn__cgo_f4c9d554b24c_Cfunc_rdma_accept byte
var _cgo_f4c9d554b24c_Cfunc_rdma_accept = unsafe.Pointer(&__cgofn__cgo_f4c9d554b24c_Cfunc_rdma_accept)

//go:cgo_unsafe_args
func _Cfunc_rdma_accept(p0 *_Ctype_struct_rdma_cm_id, p1 *_Ctype_struct_rdma_conn_param) (r1 _Ctype_int) {
	_cgo_runtime_cgocall(_cgo_f4c9d554b24c_Cfunc_rdma_accept, uintptr(unsafe.Pointer(&p0)))
	if _Cgo_always_false {
		_Cgo_use(p0)
		_Cgo_use(p1)
	}
	return
}
//go:cgo_import_static _cgo_f4c9d554b24c_Cfunc_rdma_ack_cm_event
//go:linkname __cgofn__cgo_f4c9d554b24c_Cfunc_rdma_ack_cm_event _cgo_f4c9d554b24c_Cfunc_rdma_ack_cm_event
var __cgofn__cgo_f4c9d554b24c_Cfunc_rdma_ack_cm_event byte
var _cgo_f4c9d554b24c_Cfunc_rdma_ack_cm_event = unsafe.Pointer(&__cgofn__cgo_f4c9d554b24c_Cfunc_rdma_ack_cm_event)

//go:cgo_unsafe_args
func _Cfunc_rdma_ack_cm_event(p0 *_Ctype_struct_rdma_cm_event) (r1 _Ctype_int) {
	_cgo_runtime_cgocall(_cgo_f4c9d554b24c_Cfunc_rdma_ack_cm_event, uintptr(unsafe.Pointer(&p0)))
	if _Cgo_always_false {
		_Cgo_use(p0)
	}
	return
}
//go:cgo_import_static _cgo_f4c9d554b24c_Cfunc_rdma_bind_addr
//go:linkname __cgofn__cgo_f4c9d554b24c_Cfunc_rdma_bind_addr _cgo_f4c9d554b24c_Cfunc_rdma_bind_addr
var __cgofn__cgo_f4c9d554b24c_Cfunc_rdma_bind_addr byte
var _cgo_f4c9d554b24c_Cfunc_rdma_bind_addr = unsafe.Pointer(&__cgofn__cgo_f4c9d554b24c_Cfunc_rdma_bind_addr)

//go:cgo_unsafe_args
func _Cfunc_rdma_bind_addr(p0 *_Ctype_struct_rdma_cm_id, p1 *_Ctype_struct_sockaddr) (r1 _Ctype_int) {
	_cgo_runtime_cgocall(_cgo_f4c9d554b24c_Cfunc_rdma_bind_addr, uintptr(unsafe.Pointer(&p0)))
	if _Cgo_always_false {
		_Cgo_use(p0)
		_Cgo_use(p1)
	}
	return
}
//go:cgo_import_static _cgo_f4c9d554b24c_Cfunc_rdma_connect
//go:linkname __cgofn__cgo_f4c9d554b24c_Cfunc_rdma_connect _cgo_f4c9d554b24c_Cfunc_rdma_connect
var __cgofn__cgo_f4c9d554b24c_Cfunc_rdma_connect byte
var _cgo_f4c9d554b24c_Cfunc_rdma_connect = unsafe.Pointer(&__cgofn__cgo_f4c9d554b24c_Cfunc_rdma_connect)

//go:cgo_unsafe_args
func _Cfunc_rdma_connect(p0 *_Ctype_struct_rdma_cm_id, p1 *_Ctype_struct_rdma_conn_param) (r1 _Ctype_int) {
	_cgo_runtime_cgocall(_cgo_f4c9d554b24c_Cfunc_rdma_connect, uintptr(unsafe.Pointer(&p0)))
	if _Cgo_always_false {
		_Cgo_use(p0)
		_Cgo_use(p1)
	}
	return
}
//go:cgo_import_static _cgo_f4c9d554b24c_Cfunc_rdma_create_id
//go:linkname __cgofn__cgo_f4c9d554b24c_Cfunc_rdma_create_id _cgo_f4c9d554b24c_Cfunc_rdma_create_id
var __cgofn__cgo_f4c9d554b24c_Cfunc_rdma_create_id byte
var _cgo_f4c9d554b24c_Cfunc_rdma_create_id = unsafe.Pointer(&__cgofn__cgo_f4c9d554b24c_Cfunc_rdma_create_id)

//go:cgo_unsafe_args
func _Cfunc_rdma_create_id(p0 *_Ctype_struct_rdma_event_channel, p1 **_Ctype_struct_rdma_cm_id, p2 unsafe.Pointer, p3 uint32) (r1 _Ctype_int) {
	_cgo_runtime_cgocall(_cgo_f4c9d554b24c_Cfunc_rdma_create_id, uintptr(unsafe.Pointer(&p0)))
	if _Cgo_always_false {
		_Cgo_use(p0)
		_Cgo_use(p1)
		_Cgo_use(p2)
		_Cgo_use(p3)
	}
	return
}
//go:cgo_import_static _cgo_f4c9d554b24c_Cfunc_rdma_create_qp
//go:linkname __cgofn__cgo_f4c9d554b24c_Cfunc_rdma_create_qp _cgo_f4c9d554b24c_Cfunc_rdma_create_qp
var __cgofn__cgo_f4c9d554b24c_Cfunc_rdma_create_qp byte
var _cgo_f4c9d554b24c_Cfunc_rdma_create_qp = unsafe.Pointer(&__cgofn__cgo_f4c9d554b24c_Cfunc_rdma_create_qp)

//go:cgo_unsafe_args
func _Cfunc_rdma_create_qp(p0 *_Ctype_struct_rdma_cm_id, p1 *_Ctype_struct_ibv_pd, p2 *_Ctype_struct_ibv_qp_init_attr) (r1 _Ctype_int) {
	_cgo_runtime_cgocall(_cgo_f4c9d554b24c_Cfunc_rdma_create_qp, uintptr(unsafe.Pointer(&p0)))
	if _Cgo_always_false {
		_Cgo_use(p0)
		_Cgo_use(p1)
		_Cgo_use(p2)
	}
	return
}
//go:cgo_import_static _cgo_f4c9d554b24c_Cfunc_rdma_destroy_event_channel
//go:linkname __cgofn__cgo_f4c9d554b24c_Cfunc_rdma_destroy_event_channel _cgo_f4c9d554b24c_Cfunc_rdma_destroy_event_channel
var __cgofn__cgo_f4c9d554b24c_Cfunc_rdma_destroy_event_channel byte
var _cgo_f4c9d554b24c_Cfunc_rdma_destroy_event_channel = unsafe.Pointer(&__cgofn__cgo_f4c9d554b24c_Cfunc_rdma_destroy_event_channel)

//go:cgo_unsafe_args
func _Cfunc_rdma_destroy_event_channel(p0 *_Ctype_struct_rdma_event_channel) (r1 _Ctype_void) {
	_cgo_runtime_cgocall(_cgo_f4c9d554b24c_Cfunc_rdma_destroy_event_channel, uintptr(unsafe.Pointer(&p0)))
	if _Cgo_always_false {
		_Cgo_use(p0)
	}
	return
}
//go:cgo_import_static _cgo_f4c9d554b24c_Cfunc_rdma_destroy_id
//go:linkname __cgofn__cgo_f4c9d554b24c_Cfunc_rdma_destroy_id _cgo_f4c9d554b24c_Cfunc_rdma_destroy_id
var __cgofn__cgo_f4c9d554b24c_Cfunc_rdma_destroy_id byte
var _cgo_f4c9d554b24c_Cfunc_rdma_destroy_id = unsafe.Pointer(&__cgofn__cgo_f4c9d554b24c_Cfunc_rdma_destroy_id)

//go:cgo_unsafe_args
func _Cfunc_rdma_destroy_id(p0 *_Ctype_struct_rdma_cm_id) (r1 _Ctype_int) {
	_cgo_runtime_cgocall(_cgo_f4c9d554b24c_Cfunc_rdma_destroy_id, uintptr(unsafe.Pointer(&p0)))
	if _Cgo_always_false {
		_Cgo_use(p0)
	}
	return
}
//go:cgo_import_static _cgo_f4c9d554b24c_Cfunc_rdma_disconnect
//go:linkname __cgofn__cgo_f4c9d554b24c_Cfunc_rdma_disconnect _cgo_f4c9d554b24c_Cfunc_rdma_disconnect
var __cgofn__cgo_f4c9d554b24c_Cfunc_rdma_disconnect byte
var _cgo_f4c9d554b24c_Cfunc_rdma_disconnect = unsafe.Pointer(&__cgofn__cgo_f4c9d554b24c_Cfunc_rdma_disconnect)

//go:cgo_unsafe_args
func _Cfunc_rdma_disconnect(p0 *_Ctype_struct_rdma_cm_id) (r1 _Ctype_int) {
	_cgo_runtime_cgocall(_cgo_f4c9d554b24c_Cfunc_rdma_disconnect, uintptr(unsafe.Pointer(&p0)))
	if _Cgo_always_false {
		_Cgo_use(p0)
	}
	return
}
//go:cgo_import_static _cgo_f4c9d554b24c_Cfunc_rdma_establish
//go:linkname __cgofn__cgo_f4c9d554b24c_Cfunc_rdma_establish _cgo_f4c9d554b24c_Cfunc_rdma_establish
var __cgofn__cgo_f4c9d554b24c_Cfunc_rdma_establish byte
var _cgo_f4c9d554b24c_Cfunc_rdma_establish = unsafe.Pointer(&__cgofn__cgo_f4c9d554b24c_Cfunc_rdma_establish)

//go:cgo_unsafe_args
func _Cfunc_rdma_establish(p0 *_Ctype_struct_rdma_cm_id) (r1 _Ctype_int) {
	_cgo_runtime_cgocall(_cgo_f4c9d554b24c_Cfunc_rdma_establish, uintptr(unsafe.Pointer(&p0)))
	if _Cgo_always_false {
		_Cgo_use(p0)
	}
	return
}
//go:cgo_import_static _cgo_f4c9d554b24c_Cfunc_rdma_event_str
//go:linkname __cgofn__cgo_f4c9d554b24c_Cfunc_rdma_event_str _cgo_f4c9d554b24c_Cfunc_rdma_event_str
var __cgofn__cgo_f4c9d554b24c_Cfunc_rdma_event_str byte
var _cgo_f4c9d554b24c_Cfunc_rdma_event_str = unsafe.Pointer(&__cgofn__cgo_f4c9d554b24c_Cfunc_rdma_event_str)

//go:cgo_unsafe_args
func _Cfunc_rdma_event_str(p0 uint32) (r1 *_Ctype_char) {
	_cgo_runtime_cgocall(_cgo_f4c9d554b24c_Cfunc_rdma_event_str, uintptr(unsafe.Pointer(&p0)))
	if _Cgo_always_false {
		_Cgo_use(p0)
	}
	return
}
//go:cgo_import_static _cgo_f4c9d554b24c_Cfunc_rdma_listen
//go:linkname __cgofn__cgo_f4c9d554b24c_Cfunc_rdma_listen _cgo_f4c9d554b24c_Cfunc_rdma_listen
var __cgofn__cgo_f4c9d554b24c_Cfunc_rdma_listen byte
var _cgo_f4c9d554b24c_Cfunc_rdma_listen = unsafe.Pointer(&__cgofn__cgo_f4c9d554b24c_Cfunc_rdma_listen)

//go:cgo_unsafe_args
func _Cfunc_rdma_listen(p0 *_Ctype_struct_rdma_cm_id, p1 _Ctype_int) (r1 _Ctype_int) {
	_cgo_runtime_cgocall(_cgo_f4c9d554b24c_Cfunc_rdma_listen, uintptr(unsafe.Pointer(&p0)))
	if _Cgo_always_false {
		_Cgo_use(p0)
		_Cgo_use(p1)
	}
	return
}
//go:cgo_import_static _cgo_f4c9d554b24c_Cfunc_rdma_resolve_addr
//go:linkname __cgofn__cgo_f4c9d554b24c_Cfunc_rdma_resolve_addr _cgo_f4c9d554b24c_Cfunc_rdma_resolve_addr
var __cgofn__cgo_f4c9d554b24c_Cfunc_rdma_resolve_addr byte
var _cgo_f4c9d554b24c_Cfunc_rdma_resolve_addr = unsafe.Pointer(&__cgofn__cgo_f4c9d554b24c_Cfunc_rdma_resolve_addr)

//go:cgo_unsafe_args
func _Cfunc_rdma_resolve_addr(p0 *_Ctype_struct_rdma_cm_id, p1 *_Ctype_struct_sockaddr, p2 *_Ctype_struct_sockaddr, p3 _Ctype_int) (r1 _Ctype_int) {
	_cgo_runtime_cgocall(_cgo_f4c9d554b24c_Cfunc_rdma_resolve_addr, uintptr(unsafe.Pointer(&p0)))
	if _Cgo_always_false {
		_Cgo_use(p0)
		_Cgo_use(p1)
		_Cgo_use(p2)
		_Cgo_use(p3)
	}
	return
}
//go:cgo_import_static _cgo_f4c9d554b24c_Cfunc_rdma_resolve_route
//go:linkname __cgofn__cgo_f4c9d554b24c_Cfunc_rdma_resolve_route _cgo_f4c9d554b24c_Cfunc_rdma_resolve_route
var __cgofn__cgo_f4c9d554b24c_Cfunc_rdma_resolve_route byte
var _cgo_f4c9d554b24c_Cfunc_rdma_resolve_route = unsafe.Pointer(&__cgofn__cgo_f4c9d554b24c_Cfunc_rdma_resolve_route)

//go:cgo_unsafe_args
func _Cfunc_rdma_resolve_route(p0 *_Ctype_struct_rdma_cm_id, p1 _Ctype_int) (r1 _Ctype_int) {
	_cgo_runtime_cgocall(_cgo_f4c9d554b24c_Cfunc_rdma_resolve_route, uintptr(unsafe.Pointer(&p0)))
	if _Cgo_always_false {
		_Cgo_use(p0)
		_Cgo_use(p1)
	}
	return
}
//go:cgo_import_static _cgo_f4c9d554b24c_Cfunc_reg_mr_wrapper
//go:linkname __cgofn__cgo_f4c9d554b24c_Cfunc_reg_mr_wrapper _cgo_f4c9d554b24c_Cfunc_reg_mr_wrapper
var __cgofn__cgo_f4c9d554b24c_Cfunc_reg_mr_wrapper byte
var _cgo_f4c9d554b24c_Cfunc_reg_mr_wrapper = unsafe.Pointer(&__cgofn__cgo_f4c9d554b24c_Cfunc_reg_mr_wrapper)

//go:cgo_unsafe_args
func _Cfunc_reg_mr_wrapper(p0 *_Ctype_struct_ibv_pd, p1 unsafe.Pointer, p2 _Ctype_size_t, p3 _Ctype_int, p4 **_Ctype_struct_ibv_mr) (r1 _Ctype_int) {
	_cgo_runtime_cgocall(_cgo_f4c9d554b24c_Cfunc_reg_mr_wrapper, uintptr(unsafe.Pointer(&p0)))
	if _Cgo_always_false {
		_Cgo_use(p0)
		_Cgo_use(p1)
		_Cgo_use(p2)
		_Cgo_use(p3)
		_Cgo_use(p4)
	}
	return
}
//go:cgo_import_static _cgo_f4c9d554b24c_Cfunc_resolve_addr
//go:linkname __cgofn__cgo_f4c9d554b24c_Cfunc_resolve_addr _cgo_f4c9d554b24c_Cfunc_resolve_addr
var __cgofn__cgo_f4c9d554b24c_Cfunc_resolve_addr byte
var _cgo_f4c9d554b24c_Cfunc_resolve_addr = unsafe.Pointer(&__cgofn__cgo_f4c9d554b24c_Cfunc_resolve_addr)

//go:cgo_unsafe_args
func _Cfunc_resolve_addr(p0 *_Ctype_char, p1 *_Ctype_struct_sockaddr) (r1 _Ctype_int) {
	_cgo_runtime_cgocall(_cgo_f4c9d554b24c_Cfunc_resolve_addr, uintptr(unsafe.Pointer(&p0)))
	if _Cgo_always_false {
		_Cgo_use(p0)
		_Cgo_use(p1)
	}
	return
}
//go:cgo_import_static _cgo_f4c9d554b24c_Cfunc_self_modify_qp
//go:linkname __cgofn__cgo_f4c9d554b24c_Cfunc_self_modify_qp _cgo_f4c9d554b24c_Cfunc_self_modify_qp
var __cgofn__cgo_f4c9d554b24c_Cfunc_self_modify_qp byte
var _cgo_f4c9d554b24c_Cfunc_self_modify_qp = unsafe.Pointer(&__cgofn__cgo_f4c9d554b24c_Cfunc_self_modify_qp)

//go:cgo_unsafe_args
func _Cfunc_self_modify_qp(p0 *_Ctype_struct_ibv_qp, p1 *_Ctype_struct_rdma_cm_id) (r1 _Ctype_int) {
	_cgo_runtime_cgocall(_cgo_f4c9d554b24c_Cfunc_self_modify_qp, uintptr(unsafe.Pointer(&p0)))
	if _Cgo_always_false {
		_Cgo_use(p0)
		_Cgo_use(p1)
	}
	return
}
//go:cgo_import_static _cgo_f4c9d554b24c_Cfunc_set_rdma_read_wr
//go:linkname __cgofn__cgo_f4c9d554b24c_Cfunc_set_rdma_read_wr _cgo_f4c9d554b24c_Cfunc_set_rdma_read_wr
var __cgofn__cgo_f4c9d554b24c_Cfunc_set_rdma_read_wr byte
var _cgo_f4c9d554b24c_Cfunc_set_rdma_read_wr = unsafe.Pointer(&__cgofn__cgo_f4c9d554b24c_Cfunc_set_rdma_read_wr)

//go:cgo_unsafe_args
func _Cfunc_set_rdma_read_wr(p0 *_Ctype_struct_ibv_send_wr, p1 _Ctype_uint32_t, p2 _Ctype_uint64_t, p3 _Ctype_uint32_t) (r1 _Ctype_void) {
	_cgo_runtime_cgocall(_cgo_f4c9d554b24c_Cfunc_set_rdma_read_wr, uintptr(unsafe.Pointer(&p0)))
	if _Cgo_always_false {
		_Cgo_use(p0)
		_Cgo_use(p1)
		_Cgo_use(p2)
		_Cgo_use(p3)
	}
	return
}
//go:cgo_import_static _cgo_f4c9d554b24c_Cfunc_set_rdma_write_wr
//go:linkname __cgofn__cgo_f4c9d554b24c_Cfunc_set_rdma_write_wr _cgo_f4c9d554b24c_Cfunc_set_rdma_write_wr
var __cgofn__cgo_f4c9d554b24c_Cfunc_set_rdma_write_wr byte
var _cgo_f4c9d554b24c_Cfunc_set_rdma_write_wr = unsafe.Pointer(&__cgofn__cgo_f4c9d554b24c_Cfunc_set_rdma_write_wr)

//go:cgo_unsafe_args
func _Cfunc_set_rdma_write_wr(p0 *_Ctype_struct_ibv_send_wr, p1 _Ctype_uint32_t, p2 _Ctype_uint64_t, p3 _Ctype_uint32_t) (r1 _Ctype_void) {
	_cgo_runtime_cgocall(_cgo_f4c9d554b24c_Cfunc_set_rdma_write_wr, uintptr(unsafe.Pointer(&p0)))
	if _Cgo_always_false {
		_Cgo_use(p0)
		_Cgo_use(p1)
		_Cgo_use(p2)
		_Cgo_use(p3)
	}
	return
}
//go:cgo_import_static _cgo_f4c9d554b24c_Cfunc_set_sockaddr_port
//go:linkname __cgofn__cgo_f4c9d554b24c_Cfunc_set_sockaddr_port _cgo_f4c9d554b24c_Cfunc_set_sockaddr_port
var __cgofn__cgo_f4c9d554b24c_Cfunc_set_sockaddr_port byte
var _cgo_f4c9d554b24c_Cfunc_set_sockaddr_port = unsafe.Pointer(&__cgofn__cgo_f4c9d554b24c_Cfunc_set_sockaddr_port)

//go:cgo_unsafe_args
func _Cfunc_set_sockaddr_port(p0 *_Ctype_struct_sockaddr, p1 _Ctype_uint16_t) (r1 _Ctype_void) {
	_cgo_runtime_cgocall(_cgo_f4c9d554b24c_Cfunc_set_sockaddr_port, uintptr(unsafe.Pointer(&p0)))
	if _Cgo_always_false {
		_Cgo_use(p0)
		_Cgo_use(p1)
	}
	return
}
//go:cgo_import_static _cgo_f4c9d554b24c_Cfunc_setup_rdma_wr
//go:linkname __cgofn__cgo_f4c9d554b24c_Cfunc_setup_rdma_wr _cgo_f4c9d554b24c_Cfunc_setup_rdma_wr
var __cgofn__cgo_f4c9d554b24c_Cfunc_setup_rdma_wr byte
var _cgo_f4c9d554b24c_Cfunc_setup_rdma_wr = unsafe.Pointer(&__cgofn__cgo_f4c9d554b24c_Cfunc_setup_rdma_wr)

//go:cgo_unsafe_args
func _Cfunc_setup_rdma_wr(p0 *_Ctype_struct_ibv_send_wr, p1 *_Ctype_struct_ibv_sge, p2 unsafe.Pointer, p3 _Ctype_uint32_t) (r1 _Ctype_void) {
	_cgo_runtime_cgocall(_cgo_f4c9d554b24c_Cfunc_setup_rdma_wr, uintptr(unsafe.Pointer(&p0)))
	if _Cgo_always_false {
		_Cgo_use(p0)
		_Cgo_use(p1)
		_Cgo_use(p2)
		_Cgo_use(p3)
	}
	return
}
//go:cgo_import_static _cgo_f4c9d554b24c_Cfunc_setup_recv_wr
//go:linkname __cgofn__cgo_f4c9d554b24c_Cfunc_setup_recv_wr _cgo_f4c9d554b24c_Cfunc_setup_recv_wr
var __cgofn__cgo_f4c9d554b24c_Cfunc_setup_recv_wr byte
var _cgo_f4c9d554b24c_Cfunc_setup_recv_wr = unsafe.Pointer(&__cgofn__cgo_f4c9d554b24c_Cfunc_setup_recv_wr)

//go:cgo_unsafe_args
func _Cfunc_setup_recv_wr(p0 *_Ctype_struct_ibv_recv_wr, p1 *_Ctype_struct_ibv_sge, p2 *_Ctype_struct_rping_rdma_info, p3 _Ctype_uint32_t) (r1 _Ctype_void) {
	_cgo_runtime_cgocall(_cgo_f4c9d554b24c_Cfunc_setup_recv_wr, uintptr(unsafe.Pointer(&p0)))
	if _Cgo_always_false {
		_Cgo_use(p0)
		_Cgo_use(p1)
		_Cgo_use(p2)
		_Cgo_use(p3)
	}
	return
}
//go:cgo_import_static _cgo_f4c9d554b24c_Cfunc_setup_send_wr
//go:linkname __cgofn__cgo_f4c9d554b24c_Cfunc_setup_send_wr _cgo_f4c9d554b24c_Cfunc_setup_send_wr
var __cgofn__cgo_f4c9d554b24c_Cfunc_setup_send_wr byte
var _cgo_f4c9d554b24c_Cfunc_setup_send_wr = unsafe.Pointer(&__cgofn__cgo_f4c9d554b24c_Cfunc_setup_send_wr)

//go:cgo_unsafe_args
func _Cfunc_setup_send_wr(p0 *_Ctype_struct_ibv_send_wr, p1 *_Ctype_struct_ibv_sge, p2 *_Ctype_struct_rping_rdma_info, p3 _Ctype_uint32_t) (r1 _Ctype_void) {
	_cgo_runtime_cgocall(_cgo_f4c9d554b24c_Cfunc_setup_send_wr, uintptr(unsafe.Pointer(&p0)))
	if _Cgo_always_false {
		_Cgo_use(p0)
		_Cgo_use(p1)
		_Cgo_use(p2)
		_Cgo_use(p3)
	}
	return
}
//go:cgo_import_static _cgo_f4c9d554b24c_Cfunc_write
//go:linkname __cgofn__cgo_f4c9d554b24c_Cfunc_write _cgo_f4c9d554b24c_Cfunc_write
var __cgofn__cgo_f4c9d554b24c_Cfunc_write byte
var _cgo_f4c9d554b24c_Cfunc_write = unsafe.Pointer(&__cgofn__cgo_f4c9d554b24c_Cfunc_write)

//go:cgo_unsafe_args
func _Cfunc_write(p0 _Ctype_int, p1 unsafe.Pointer, p2 _Ctype_size_t) (r1 _Ctype_ssize_t) {
	_cgo_runtime_cgocall(_cgo_f4c9d554b24c_Cfunc_write, uintptr(unsafe.Pointer(&p0)))
	if _Cgo_always_false {
		_Cgo_use(p0)
		_Cgo_use(p1)
		_Cgo_use(p2)
	}
	return
}

//go:cgo_import_static _cgo_f4c9d554b24c_Cfunc__Cmalloc
//go:linkname __cgofn__cgo_f4c9d554b24c_Cfunc__Cmalloc _cgo_f4c9d554b24c_Cfunc__Cmalloc
var __cgofn__cgo_f4c9d554b24c_Cfunc__Cmalloc byte
var _cgo_f4c9d554b24c_Cfunc__Cmalloc = unsafe.Pointer(&__cgofn__cgo_f4c9d554b24c_Cfunc__Cmalloc)

//go:linkname runtime_throw runtime.throw
func runtime_throw(string)

//go:cgo_unsafe_args
func _cgo_cmalloc(p0 uint64) (r1 unsafe.Pointer) {
	_cgo_runtime_cgocall(_cgo_f4c9d554b24c_Cfunc__Cmalloc, uintptr(unsafe.Pointer(&p0)))
	if r1 == nil {
		runtime_throw("runtime: C malloc failed")
	}
	return
}
