// Code generated by cmd/cgo; DO NOT EDIT.

//line /home/jzbmufeng/workspace/community/rdma-core/librdmacm/examples/rping-go/rping.go:1:1
package main; import _cgo_unsafe "unsafe"

/*
#cgo LDFLAGS: -lrdmacm -libverbs
#include <rdma/rdma_cma.h>
#include <infiniband/verbs.h>
#include <endian.h>
#include <string.h>
#include <stdlib.h>
#include <errno.h>
#include <netdb.h>
#include <sys/eventfd.h>
#include <sys/poll.h>
#include <unistd.h>
#include <stdio.h>

// rping_rdma_info structure matching the C definition
struct rping_rdma_info {
	uint64_t buf;   // stored in network byte order
	uint32_t rkey;  // stored in network byte order
	uint32_t size;  // stored in network byte order
};

// --- Helper functions to avoid direct errno/field access from Go ---

static int get_channel_fd(struct rdma_event_channel *ch) {
	return ch->fd;
}

static struct ibv_context *get_verbs(struct rdma_cm_id *id) {
	return id->verbs;
}

static uint8_t get_port_num(struct rdma_cm_id *id) {
	return id->port_num;
}

static struct ibv_qp *get_cm_id_qp(struct rdma_cm_id *id) {
	return id->qp;
}

static struct rdma_cm_id *get_event_id(struct rdma_cm_event *event) {
	return event->id;
}

static int get_event_event(struct rdma_cm_event *event) {
	return event->event;
}

static int get_event_status(struct rdma_cm_event *event) {
	return event->status;
}

static uint32_t get_qp_num(struct ibv_qp *qp) {
	return qp->qp_num;
}

static uint32_t get_lkey(struct ibv_mr *mr) {
	return mr->lkey;
}

static uint32_t get_rkey(struct ibv_mr *mr) {
	return mr->rkey;
}

static void fill_rdma_info(struct rping_rdma_info *info, uint64_t buf, uint32_t rkey, uint32_t size) {
	info->buf = htobe64(buf);
	info->rkey = htobe32(rkey);
	info->size = htobe32(size);
}

static uint64_t info_get_buf(struct rping_rdma_info *info) {
	return be64toh(info->buf);
}
static uint32_t info_get_rkey(struct rping_rdma_info *info) {
	return be32toh(info->rkey);
}
static uint32_t info_get_size(struct rping_rdma_info *info) {
	return be32toh(info->size);
}

static void setup_recv_wr(struct ibv_recv_wr *wr, struct ibv_sge *sgl,
                          struct rping_rdma_info *recv_buf, uint32_t lkey) {
	sgl->addr = (uint64_t)(unsigned long)recv_buf;
	sgl->length = sizeof(struct rping_rdma_info);
	sgl->lkey = lkey;
	wr->sg_list = sgl;
	wr->num_sge = 1;
	wr->next = NULL;
}

static void setup_send_wr(struct ibv_send_wr *wr, struct ibv_sge *sgl,
                          struct rping_rdma_info *send_buf, uint32_t lkey) {
	sgl->addr = (uint64_t)(unsigned long)send_buf;
	sgl->length = sizeof(struct rping_rdma_info);
	sgl->lkey = lkey;
	wr->opcode = IBV_WR_SEND;
	wr->send_flags = IBV_SEND_SIGNALED;
	wr->sg_list = sgl;
	wr->num_sge = 1;
	wr->next = NULL;
}

static void setup_rdma_wr(struct ibv_send_wr *wr, struct ibv_sge *sgl,
                          void *rdma_buf, uint32_t lkey) {
	sgl->addr = (uint64_t)(unsigned long)rdma_buf;
	sgl->lkey = lkey;
	wr->send_flags = IBV_SEND_SIGNALED;
	wr->sg_list = sgl;
	wr->num_sge = 1;
	wr->next = NULL;
}

static void set_rdma_read_wr(struct ibv_send_wr *wr, uint32_t rkey,
                             uint64_t remote_addr, uint32_t length) {
	wr->opcode = IBV_WR_RDMA_READ;
	wr->wr.rdma.rkey = rkey;
	wr->wr.rdma.remote_addr = remote_addr;
	wr->sg_list->length = length;
}

static void set_rdma_write_wr(struct ibv_send_wr *wr, uint32_t rkey,
                              uint64_t remote_addr, uint32_t length) {
	wr->opcode = IBV_WR_RDMA_WRITE;
	wr->wr.rdma.rkey = rkey;
	wr->wr.rdma.remote_addr = remote_addr;
	wr->sg_list->length = length;
}

static uint32_t get_rdma_buf_strlen(const char *buf) {
	return (uint32_t)(strlen(buf) + 1);
}

static void set_sockaddr_port(struct sockaddr *addr, uint16_t port) {
	if (addr->sa_family == AF_INET)
		((struct sockaddr_in *)addr)->sin_port = port;
	else
		((struct sockaddr_in6 *)addr)->sin6_port = port;
}

static int resolve_addr(char *dst, struct sockaddr *addr) {
	struct addrinfo *res;
	int ret = getaddrinfo(dst, NULL, NULL, &res);
	if (ret)
		return ret;
	if (res->ai_family == PF_INET)
		memcpy(addr, res->ai_addr, sizeof(struct sockaddr_in));
	else if (res->ai_family == PF_INET6)
		memcpy(addr, res->ai_addr, sizeof(struct sockaddr_in6));
	else
		ret = -1;
	freeaddrinfo(res);
	return ret;
}

static void init_conn_param(struct rdma_conn_param *param, int qp_num, int self_create_qp) {
	memset(param, 0, sizeof(*param));
	param->responder_resources = 1;
	param->initiator_depth = 1;
	param->retry_count = 7;
	param->rnr_retry_count = 7;
	if (self_create_qp)
		param->qp_num = qp_num;
}

static int self_modify_qp(struct ibv_qp *qp, struct rdma_cm_id *id) {
	struct ibv_qp_attr qp_attr;
	int qp_attr_mask, ret;

	qp_attr.qp_state = IBV_QPS_INIT;
	ret = rdma_init_qp_attr(id, &qp_attr, &qp_attr_mask);
	if (ret) return ret;
	ret = ibv_modify_qp(qp, &qp_attr, qp_attr_mask);
	if (ret) return ret;

	qp_attr.qp_state = IBV_QPS_RTR;
	ret = rdma_init_qp_attr(id, &qp_attr, &qp_attr_mask);
	if (ret) return ret;
	ret = ibv_modify_qp(qp, &qp_attr, qp_attr_mask);
	if (ret) return ret;

	qp_attr.qp_state = IBV_QPS_RTS;
	ret = rdma_init_qp_attr(id, &qp_attr, &qp_attr_mask);
	if (ret) return ret;
	return ibv_modify_qp(qp, &qp_attr, qp_attr_mask);
}

// Wrapper for rdma_create_event_channel that returns errno
static int create_event_channel_wrapper(struct rdma_event_channel **ch) {
	*ch = rdma_create_event_channel();
	if (!*ch)
		return errno;
	return 0;
}

// Wrapper for ibv_alloc_pd that returns errno
static int alloc_pd_wrapper(struct ibv_context *ctx, struct ibv_pd **pd) {
	*pd = ibv_alloc_pd(ctx);
	if (!*pd)
		return errno;
	return 0;
}

// Wrapper for ibv_create_comp_channel that returns errno
static int create_comp_channel_wrapper(struct ibv_context *ctx, struct ibv_comp_channel **ch) {
	*ch = ibv_create_comp_channel(ctx);
	if (!*ch)
		return errno;
	return 0;
}

// Wrapper for ibv_create_cq that returns errno
static int create_cq_wrapper(struct ibv_context *ctx, int cqe, struct ibv_comp_channel *ch,
                             struct ibv_cq **cq) {
	*cq = ibv_create_cq(ctx, cqe, NULL, ch, 0);
	if (!*cq)
		return errno;
	return 0;
}

// Wrapper for ibv_reg_mr that returns errno
static int reg_mr_wrapper(struct ibv_pd *pd, void *buf, size_t len, int access, struct ibv_mr **mr) {
	*mr = ibv_reg_mr(pd, buf, len, access);
	if (!*mr)
		return errno;
	return 0;
}

// Wrapper for ibv_create_qp that returns errno
static int create_qp_wrapper(struct ibv_pd *pd, struct ibv_qp_init_attr *attr, struct ibv_qp **qp) {
	*qp = ibv_create_qp(pd, attr);
	if (!*qp)
		return errno;
	return 0;
}

// Wrapper for getnameinfo
static void getnameinfo_wrapper(struct sockaddr *addr, socklen_t addrlen,
                                char *host, socklen_t hostlen) {
	getnameinfo(addr, addrlen, host, hostlen, NULL, 0, NI_NUMERICHOST);
}

// Byte order wrappers for Go
static uint16_t go_htobe16(uint16_t v) { return htobe16(v); }
static uint16_t go_be16toh(uint16_t v) { return be16toh(v); }
static uint32_t go_htobe32(uint32_t v) { return htobe32(v); }
static uint32_t go_be32toh(uint32_t v) { return be32toh(v); }
static uint64_t go_htobe64(uint64_t v) { return htobe64(v); }
static uint64_t go_be64toh(uint64_t v) { return be64toh(v); }

// Wrapper for poll with EINTR handling
static int poll_wrapper(struct pollfd *fds, nfds_t nfds, int timeout) {
	int ret;
	do {
		ret = poll(fds, nfds, timeout);
	} while (ret == -1 && errno == EINTR);
	if (ret == -1)
		return -errno;
	return ret;
}

// Wrapper for rdma_get_cm_event
static int get_cm_event_wrapper(struct rdma_event_channel *channel, struct rdma_cm_event **event) {
	int ret = rdma_get_cm_event(channel, event);
	if (ret)
		return -errno;
	return 0;
}

// Wrapper for ibv_get_cq_event
static int get_cq_event_wrapper(struct ibv_comp_channel *channel, struct ibv_cq **cq, void **ctx) {
	int ret = ibv_get_cq_event(channel, cq, ctx);
	if (ret)
		return -errno;
	return 0;
}
*/
import _ "unsafe"
import (
	"flag"
	"fmt"
	"net"
	"os"
	"runtime"
	"sync"
	"syscall"
	"time"
	"unsafe"
)

// --- Constants ---
const (
	rpingBufSize    = 64 * 1024
	rpingSQDepth    = 16
	rpingMinBufSize = 16
	rpingMsgFmt     = "rdma-ping-%d: "
	defaultPort     = 7174
)

// --- TestState represents the state machine states ---
type TestState int

const (
	StateIdle             TestState = iota + 1
	StateConnectRequest
	StateAddrResolved
	StateRouteResolved
	StateConnected
	StateRDMAReadAdv
	StateRDMAReadComplete
	StateRDMAWriteAdv
	StateRDMAWriteComplete
	StateDisconnected
	StateError
)

func (s TestState) String() string {
	names := map[TestState]string{
		StateIdle: "IDLE", StateConnectRequest: "CONNECT_REQUEST",
		StateAddrResolved: "ADDR_RESOLVED", StateRouteResolved: "ROUTE_RESOLVED",
		StateConnected: "CONNECTED", StateRDMAReadAdv: "RDMA_READ_ADV",
		StateRDMAReadComplete: "RDMA_READ_COMPLETE", StateRDMAWriteAdv: "RDMA_WRITE_ADV",
		StateRDMAWriteComplete: "RDMA_WRITE_COMPLETE", StateDisconnected: "DISCONNECTED",
		StateError: "ERROR",
	}
	if n, ok := names[s]; ok {
		return n
	}
	return fmt.Sprintf("UNKNOWN(%d)", s)
}

// --- RPingCB is the control block ---
type RPingCB struct {
	mu    sync.Mutex
	cond  *sync.Cond
	state TestState

	server bool

	// RDMA resources
	pd      * /*line :341:11*/_Ctype_struct_ibv_pd /*line :341:26*/
	channel * /*line :342:11*/_Ctype_struct_ibv_comp_channel /*line :342:36*/
	cq      * /*line :343:11*/_Ctype_struct_ibv_cq /*line :343:26*/
	qp      * /*line :344:11*/_Ctype_struct_ibv_qp /*line :344:26*/

	// Recv side
	recvBuf  /*line :347:10*/_Ctype_struct_rping_rdma_info /*line :347:34*/
	recvMR  * /*line :348:11*/_Ctype_struct_ibv_mr /*line :348:26*/
	rqWr     /*line :349:10*/_Ctype_struct_ibv_recv_wr /*line :349:30*/
	recvSGL  /*line :350:10*/_Ctype_struct_ibv_sge /*line :350:26*/

	// Send side
	sendBuf  /*line :353:10*/_Ctype_struct_rping_rdma_info /*line :353:34*/
	sendMR  * /*line :354:11*/_Ctype_struct_ibv_mr /*line :354:26*/
	sqWr     /*line :355:10*/_Ctype_struct_ibv_send_wr /*line :355:30*/
	sendSGL  /*line :356:10*/_Ctype_struct_ibv_sge /*line :356:26*/

	// RDMA side
	rdmaBuf []byte
	rdmaMR  * /*line :360:11*/_Ctype_struct_ibv_mr /*line :360:26*/
	rdmaWr   /*line :361:10*/_Ctype_struct_ibv_send_wr /*line :361:30*/
	rdmaSGL  /*line :362:10*/_Ctype_struct_ibv_sge /*line :362:26*/

	// Remote RDMA info
	remoteRkey uint32
	remoteAddr uint64
	remoteLen  uint32

	// Client start buffer
	startBuf []byte
	startMR  * /*line :371:12*/_Ctype_struct_ibv_mr /*line :371:27*/

	// CM
	cmChannel * /*line :374:13*/_Ctype_struct_rdma_event_channel /*line :374:40*/
	cmID      * /*line :375:13*/_Ctype_struct_rdma_cm_id /*line :375:32*/
	childCMID * /*line :376:13*/_Ctype_struct_rdma_cm_id /*line :376:32*/

	// Address
	sin      /*line :379:10*/_Ctype_struct_sockaddr_storage /*line :379:35*/
	ssource  /*line :380:10*/_Ctype_struct_sockaddr_storage /*line :380:35*/
	port    uint16

	// Options
	verbose      int
	selfCreateQP bool
	count        int
	size         int
	validate     bool

	// Event fd
	eventfd  /*line :391:10*/_Ctype_int /*line :391:15*/

	// Goroutine done channels
	cqDone chan struct{}
	cmDone chan struct{}
}

func newRPingCB() *RPingCB {
	cb := &RPingCB{
		state:  StateIdle,
		size:   64,
		port:   uint16(( /*line :402:18*/_Cfunc_go_htobe16 /*line :402:29*/)( /*line :402:31*/_Ctype_ushort /*line :402:39*/(defaultPort))),
		cqDone: make(chan struct{}),
		cmDone: make(chan struct{}),
	}
	cb.sin.ss_family = ( /*line :406:21*/_Ciconst_PF_INET /*line :406:29*/)
	cb.cond = sync.NewCond(&cb.mu)
	return cb
}

func (cb *RPingCB) setState(s TestState) {
	cb.mu.Lock()
	cb.state = s
	cb.cond.Broadcast()
	cb.mu.Unlock()
}

func (cb *RPingCB) getState() TestState {
	cb.mu.Lock()
	defer cb.mu.Unlock()
	return cb.state
}

// waitState blocks until state matches one of the target states
func (cb *RPingCB) waitState(targets ...TestState) TestState {
	cb.mu.Lock()
	defer cb.mu.Unlock()
	for {
		for _, t := range targets {
			if cb.state == t {
				return cb.state
			}
		}
		cb.cond.Wait()
	}
}

// --- Byte order helpers ---
func htobe16(v uint16) uint16 { return uint16(( /*line :439:47*/_Cfunc_go_htobe16 /*line :439:58*/)( /*line :439:60*/_Ctype_ushort /*line :439:68*/(v))) }
func be16toh(v uint16) uint16 { return uint16(( /*line :440:47*/_Cfunc_go_be16toh /*line :440:58*/)( /*line :440:60*/_Ctype_ushort /*line :440:68*/(v))) }

// --- Address resolution ---
func resolveAddr(dst string) ( /*line :443:31*/_Ctype_struct_sockaddr_storage /*line :443:56*/, error) {
	cDst := ( /*line :444:10*/_Cfunc_CString /*line :444:18*/)(dst)
	defer func() func() { _cgo0 := /*line :445:15*/unsafe.Pointer(cDst); return func() { _cgoCheckPointer(_cgo0, nil); /*line :445:36*/_Cfunc_free(_cgo0); }}()()
	var addr  /*line :446:11*/_Ctype_struct_sockaddr_storage /*line :446:36*/
	ret := ( /*line :447:9*/_Cfunc_resolve_addr /*line :447:22*/)(cDst, (* /*line :447:32*/_Ctype_struct_sockaddr /*line :447:49*/)(unsafe.Pointer(&addr)))
	if ret != 0 {
		return addr, fmt.Errorf("resolve_addr failed for %s", dst)
	}
	return addr, nil
}

// --- CM event handler ---
func (cb *RPingCB) cmaEventHandler(cmaID * /*line :455:43*/_Ctype_struct_rdma_cm_id /*line :455:62*/, event * /*line :455:71*/_Ctype_struct_rdma_cm_event /*line :455:93*/)  /*line :455:95*/_Ctype_int /*line :455:100*/ {
	eventType := func() _Ctype_int{ _cgo0 := /*line :456:33*/event; _cgoCheckPointer(_cgo0, nil); return /*line :456:39*/_Cfunc_get_event_event(_cgo0); }()

	switch eventType {
	case ( /*line :459:7*/_Ciconst_RDMA_CM_EVENT_ADDR_RESOLVED /*line :459:35*/):
		cb.setState(StateAddrResolved)
		ret := func() _Ctype_int{ _cgo0 := /*line :461:31*/cmaID; var _cgo1 _Ctype_int = /*line :461:38*/2000; _cgoCheckPointer(_cgo0, nil); return /*line :461:43*/_Cfunc_rdma_resolve_route(_cgo0, _cgo1); }()
		if ret != 0 {
			cb.setState(StateError)
		}

	case ( /*line :466:7*/_Ciconst_RDMA_CM_EVENT_ROUTE_RESOLVED /*line :466:36*/):
		cb.setState(StateRouteResolved)

	case ( /*line :469:7*/_Ciconst_RDMA_CM_EVENT_CONNECT_REQUEST /*line :469:37*/):
		cb.mu.Lock()
		cb.childCMID = cmaID
		cb.state = StateConnectRequest
		cb.cond.Broadcast()
		cb.mu.Unlock()

	case ( /*line :476:7*/_Ciconst_RDMA_CM_EVENT_CONNECT_RESPONSE /*line :476:38*/):
		cb.setState(StateConnected)

	case ( /*line :479:7*/_Ciconst_RDMA_CM_EVENT_ESTABLISHED /*line :479:33*/):
		if !cb.server {
			cb.setState(StateConnected)
		} else {
			cb.mu.Lock()
			cb.cond.Broadcast()
			cb.mu.Unlock()
		}

	case ( /*line :488:7*/_Ciconst_RDMA_CM_EVENT_ADDR_ERROR /*line :488:32*/), ( /*line :488:35*/_Ciconst_RDMA_CM_EVENT_ROUTE_ERROR /*line :488:61*/),
		( /*line :489:3*/_Ciconst_RDMA_CM_EVENT_CONNECT_ERROR /*line :489:31*/), ( /*line :489:34*/_Ciconst_RDMA_CM_EVENT_UNREACHABLE /*line :489:60*/),
		( /*line :490:3*/_Ciconst_RDMA_CM_EVENT_REJECTED /*line :490:26*/):
		fmt.Fprintf(os.Stderr, "cma event %s, error %d\n",
			( /*line :492:4*/_Cfunc_GoString /*line :492:13*/)(( /*line :492:15*/_Cfunc_rdma_event_str /*line :492:30*/)(eventType)), func() _Ctype_int{ _cgo0 := /*line :492:64*/event; _cgoCheckPointer(_cgo0, nil); return /*line :492:70*/_Cfunc_get_event_status(_cgo0); }())
		cb.mu.Lock()
		cb.cond.Broadcast()
		cb.mu.Unlock()
		return -1

	case ( /*line :498:7*/_Ciconst_RDMA_CM_EVENT_DISCONNECTED /*line :498:34*/):
		role := "client"
		if cb.server {
			role = "server"
		}
		fmt.Fprintf(os.Stderr, "%s DISCONNECT EVENT...\n", role)
		cb.setState(StateDisconnected)

	case ( /*line :506:7*/_Ciconst_RDMA_CM_EVENT_DEVICE_REMOVAL /*line :506:36*/):
		fmt.Fprintf(os.Stderr, "cma detected device removal!!!!\n")
		cb.setState(StateError)
		return -1

	default:
		fmt.Fprintf(os.Stderr, "unhandled event: %s, ignoring\n", ( /*line :512:61*/_Cfunc_GoString /*line :512:70*/)(( /*line :512:72*/_Cfunc_rdma_event_str /*line :512:87*/)(eventType)))
	}

	return 0
}

// --- CQ event handler ---
func (cb *RPingCB) cqEventHandler()  /*line :519:37*/_Ctype_int /*line :519:42*/ {
	var wc  /*line :520:9*/_Ctype_struct_ibv_wc /*line :520:24*/
	var badWr * /*line :521:13*/_Ctype_struct_ibv_recv_wr /*line :521:33*/
	var flushed  /*line :522:14*/_Ctype_int /*line :522:19*/ = 0

	for {
		ret := func() _Ctype_int{ _cgo0 := /*line :525:24*/cb.cq; var _cgo1 _Ctype_int = /*line :525:31*/1; var _cgo2 *_Ctype_struct_ibv_wc = /*line :525:34*/&wc; _cgoCheckPointer(_cgo0, nil); return /*line :525:38*/_Cfunc_ibv_poll_cq(_cgo0, _cgo1, _cgo2); }()
		if ret == 0 {
			break
		}
		if ret < 0 {
			fmt.Fprintf(os.Stderr, "poll error %d\n", ret)
			cb.setState(StateError)
			return  /*line :532:11*/_Ctype_int /*line :532:16*/(ret)
		}

		if wc.status != 0 {
			if wc.status == ( /*line :536:20*/_Ciconst_IBV_WC_WR_FLUSH_ERR /*line :536:40*/) {
				flushed = 1
				continue
			}
			fmt.Fprintf(os.Stderr, "cq completion failed status %d\n", wc.status)
			cb.setState(StateError)
			return -1
		}

		switch wc.opcode {
		case ( /*line :546:8*/_Ciconst_IBV_WC_SEND /*line :546:20*/):
			// nothing

		case ( /*line :549:8*/_Ciconst_IBV_WC_RDMA_WRITE /*line :549:26*/):
			cb.setState(StateRDMAWriteComplete)

		case ( /*line :552:8*/_Ciconst_IBV_WC_RDMA_READ /*line :552:25*/):
			cb.setState(StateRDMAReadComplete)

		case ( /*line :555:8*/_Ciconst_IBV_WC_RECV /*line :555:20*/):
			if ( /*line :556:7*/_Ciconst_sizeof_struct_rping_rdma_info /*line :556:37*/) !=  /*line :556:42*/_Ctype_uint /*line :556:48*/(wc.byte_len) {
				fmt.Fprintf(os.Stderr, "Received bogus data, size %d\n", wc.byte_len)
				cb.setState(StateError)
				return -1
			}

			if cb.server {
				cb.remoteRkey = uint32(( /*line :563:28*/_Cfunc_info_get_rkey /*line :563:42*/)(&cb.recvBuf))
				cb.remoteAddr = uint64(( /*line :564:28*/_Cfunc_info_get_buf /*line :564:41*/)(&cb.recvBuf))
				cb.remoteLen = uint32(( /*line :565:27*/_Cfunc_info_get_size /*line :565:41*/)(&cb.recvBuf))

				state := cb.getState()
				if state <= StateConnected || state == StateRDMAWriteComplete {
					cb.setState(StateRDMAReadAdv)
				} else {
					cb.setState(StateRDMAWriteAdv)
				}
			} else {
				state := cb.getState()
				if state == StateRDMAReadAdv {
					cb.setState(StateRDMAWriteAdv)
				} else {
					cb.setState(StateRDMAWriteComplete)
				}
			}

			ret := func() _Ctype_int{ _cgo0 := /*line :582:27*/cb.qp; _cgoBase1 := /*line :582:34*/&cb.rqWr; _cgo1 := _cgoBase1; _cgoBase2 := /*line :582:44*/&badWr; _cgo2 := _cgoBase2; _cgoCheckPointer(_cgo0, nil); _cgoCheckPointer(_cgoBase1, 0 == 0); _cgoCheckPointer(_cgoBase2, 0 == 0); return /*line :582:51*/_Cfunc_ibv_post_recv(_cgo0, _cgo1, _cgo2); }()
			if ret != 0 {
				fmt.Fprintf(os.Stderr, "post recv error: %d\n", ret)
				cb.setState(StateError)
				return -1
			}

		default:
			fmt.Fprintf(os.Stderr, "unknown completion opcode %d\n", wc.opcode)
			cb.setState(StateError)
			return -1
		}
	}

	return flushed
}

// --- QP setup ---
func (cb *RPingCB) setupQP(cmID * /*line :600:34*/_Ctype_struct_ibv_cm_id /*line :600:52*/) error {
	verbs := func() *_Ctype_struct_ibv_context{ _cgo0 := /*line :601:23*/cmID; _cgoCheckPointer(_cgo0, nil); return /*line :601:28*/_Cfunc_get_verbs(_cgo0); }()

	var pd * /*line :603:10*/_Ctype_struct_ibv_pd /*line :603:25*/
	if ret := func() _Ctype_int{ _cgo0 := /*line :604:31*/verbs; _cgoBase1 := /*line :604:38*/&pd; _cgo1 := _cgoBase1; _cgoCheckPointer(_cgo0, nil); _cgoCheckPointer(_cgoBase1, 0 == 0); return /*line :604:42*/_Cfunc_alloc_pd_wrapper(_cgo0, _cgo1); }(); ret != 0 {
		return fmt.Errorf("ibv_alloc_pd failed: %d", ret)
	}
	cb.pd = pd

	var ch * /*line :609:10*/_Ctype_struct_ibv_comp_channel /*line :609:35*/
	if ret := func() _Ctype_int{ _cgo0 := /*line :610:42*/verbs; _cgoBase1 := /*line :610:49*/&ch; _cgo1 := _cgoBase1; _cgoCheckPointer(_cgo0, nil); _cgoCheckPointer(_cgoBase1, 0 == 0); return /*line :610:53*/_Cfunc_create_comp_channel_wrapper(_cgo0, _cgo1); }(); ret != 0 {
		func() _Ctype_int{ _cgo0 := /*line :611:20*/cb.pd; _cgoCheckPointer(_cgo0, nil); return /*line :611:26*/_Cfunc_ibv_dealloc_pd(_cgo0); }()
		return fmt.Errorf("ibv_create_comp_channel failed: %d", ret)
	}
	cb.channel = ch

	var cq * /*line :616:10*/_Ctype_struct_ibv_cq /*line :616:25*/
	if ret := func() _Ctype_int{ _cgo0 := /*line :617:32*/verbs; var _cgo1 _Ctype_int = /*line :617:39*/rpingSQDepth * 2; _cgo2 := /*line :617:55*/cb.channel; _cgoBase3 := /*line :617:67*/&cq; _cgo3 := _cgoBase3; _cgoCheckPointer(_cgo0, nil); _cgoCheckPointer(_cgo2, nil); _cgoCheckPointer(_cgoBase3, 0 == 0); return /*line :617:71*/_Cfunc_create_cq_wrapper(_cgo0, _cgo1, _cgo2, _cgo3); }(); ret != 0 {
		func() _Ctype_int{ _cgo0 := /*line :618:30*/cb.channel; _cgoCheckPointer(_cgo0, nil); return /*line :618:41*/_Cfunc_ibv_destroy_comp_channel(_cgo0); }()
		func() _Ctype_int{ _cgo0 := /*line :619:20*/cb.pd; _cgoCheckPointer(_cgo0, nil); return /*line :619:26*/_Cfunc_ibv_dealloc_pd(_cgo0); }()
		return fmt.Errorf("ibv_create_cq failed: %d", ret)
	}
	cb.cq = cq

	if ret := func() _Ctype_int{ _cgo0 := /*line :624:32*/cb.cq; var _cgo1 _Ctype_int = /*line :624:39*/0; _cgoCheckPointer(_cgo0, nil); return /*line :624:41*/_Cfunc_ibv_req_notify_cq(_cgo0, _cgo1); }(); ret != 0 {
		func() _Ctype_int{ _cgo0 := /*line :625:20*/cb.cq; _cgoCheckPointer(_cgo0, nil); return /*line :625:26*/_Cfunc_ibv_destroy_cq(_cgo0); }()
		func() _Ctype_int{ _cgo0 := /*line :626:30*/cb.channel; _cgoCheckPointer(_cgo0, nil); return /*line :626:41*/_Cfunc_ibv_destroy_comp_channel(_cgo0); }()
		func() _Ctype_int{ _cgo0 := /*line :627:20*/cb.pd; _cgoCheckPointer(_cgo0, nil); return /*line :627:26*/_Cfunc_ibv_dealloc_pd(_cgo0); }()
		return fmt.Errorf("ibv_req_notify_cq failed")
	}

	if err := cb.createQP(cmID); err != nil {
		func() _Ctype_int{ _cgo0 := /*line :632:20*/cb.cq; _cgoCheckPointer(_cgo0, nil); return /*line :632:26*/_Cfunc_ibv_destroy_cq(_cgo0); }()
		func() _Ctype_int{ _cgo0 := /*line :633:30*/cb.channel; _cgoCheckPointer(_cgo0, nil); return /*line :633:41*/_Cfunc_ibv_destroy_comp_channel(_cgo0); }()
		func() _Ctype_int{ _cgo0 := /*line :634:20*/cb.pd; _cgoCheckPointer(_cgo0, nil); return /*line :634:26*/_Cfunc_ibv_dealloc_pd(_cgo0); }()
		return err
	}

	return nil
}

func (cb *RPingCB) createQP(cmID * /*line :641:35*/_Ctype_struct_ibv_cm_id /*line :641:53*/) error {
	var initAttr  /*line :642:15*/_Ctype_struct_ibv_qp_init_attr /*line :642:40*/
	func() _cgo_unsafe.Pointer{ _cgoBase0 := /*line :643:26*/&initAttr; _cgo0 := /*line :643:11*/unsafe.Pointer(_cgoBase0); var _cgo1 _Ctype_int = /*line :643:38*/0; var _cgo2 _Ctype_size_t = /*line :643:41*/_Ciconst_sizeof_struct_ibv_qp_init_attr /*line :643:73*/; _cgoCheckPointer(_cgoBase0, 0 == 0); return /*line :643:74*/_Cfunc_memset(_cgo0, _cgo1, _cgo2); }()
	initAttr.cap.max_send_wr = rpingSQDepth
	initAttr.cap.max_recv_wr = 2
	initAttr.cap.max_recv_sge = 1
	initAttr.cap.max_send_sge = 1
	initAttr.qp_type = ( /*line :648:21*/_Ciconst_IBV_QPT_RC /*line :648:32*/)
	initAttr.send_cq = cb.cq
	initAttr.recv_cq = cb.cq

	var id * /*line :652:10*/_Ctype_struct_ibv_cm_id /*line :652:28*/
	if cb.server {
		id = cb.childCMID
	} else {
		id = cb.cmID
	}

	if cb.selfCreateQP {
		var qp * /*line :660:11*/_Ctype_struct_ibv_qp /*line :660:26*/
		if ret := func() _Ctype_int{ _cgo0 := /*line :661:33*/cb.pd; _cgoBase1 := /*line :661:40*/&initAttr; _cgo1 := _cgoBase1; _cgoBase2 := /*line :661:51*/&qp; _cgo2 := _cgoBase2; _cgoCheckPointer(_cgo0, nil); _cgoCheckPointer(_cgoBase1, 0 == 0); _cgoCheckPointer(_cgoBase2, 0 == 0); return /*line :661:55*/_Cfunc_create_qp_wrapper(_cgo0, _cgo1, _cgo2); }(); ret != 0 {
			return fmt.Errorf("ibv_create_qp failed: %d", ret)
		}
		cb.qp = qp

		var attr  /*line :666:12*/_Ctype_struct_ibv_qp_attr /*line :666:32*/
		func() _cgo_unsafe.Pointer{ _cgoBase0 := /*line :667:27*/&attr; _cgo0 := /*line :667:12*/unsafe.Pointer(_cgoBase0); var _cgo1 _Ctype_int = /*line :667:35*/0; var _cgo2 _Ctype_size_t = /*line :667:38*/_Ciconst_sizeof_struct_ibv_qp_attr /*line :667:65*/; _cgoCheckPointer(_cgoBase0, 0 == 0); return /*line :667:66*/_Cfunc_memset(_cgo0, _cgo1, _cgo2); }()
		attr.qp_state = ( /*line :668:19*/_Ciconst_IBV_QPS_INIT /*line :668:32*/)
		attr.pkey_index = 0
		attr.port_num = func() _Ctype_uint8_t{ _cgo0 := /*line :670:34*/id; _cgoCheckPointer(_cgo0, nil); return /*line :670:37*/_Cfunc_get_port_num(_cgo0); }()
		attr.qp_access_flags = 0

		ret := func() _Ctype_int{ _cgo0 := /*line :673:26*/cb.qp; var _cgo1 *_Ctype_struct_ibv_qp_attr = /*line :673:33*/&attr; var _cgo2 _Ctype_int = _Ciconst_IBV_QP_STATE /*line :674:18*/ | _Ciconst_IBV_QP_PKEY_INDEX /*line :674:38*/ | _Ciconst_IBV_QP_PORT /*line :674:52*/ | _Ciconst_IBV_QP_ACCESS_FLAGS /*line :674:74*/; _cgoCheckPointer(_cgo0, nil); return /*line :674:75*/_Cfunc_ibv_modify_qp(_cgo0, _cgo1, _cgo2); }()
		if ret != 0 {
			func() _Ctype_int{ _cgo0 := /*line :676:21*/cb.qp; _cgoCheckPointer(_cgo0, nil); return /*line :676:27*/_Cfunc_ibv_destroy_qp(_cgo0); }()
			return fmt.Errorf("ibv_modify_qp to INIT failed")
		}
		return nil
	}

	ret := func() _Ctype_int{ _cgo0 := /*line :682:26*/id; _cgo1 := /*line :682:30*/cb.pd; _cgoBase2 := /*line :682:37*/&initAttr; _cgo2 := _cgoBase2; _cgoCheckPointer(_cgo0, nil); _cgoCheckPointer(_cgo1, nil); _cgoCheckPointer(_cgoBase2, 0 == 0); return /*line :682:47*/_Cfunc_rdma_create_qp(_cgo0, _cgo1, _cgo2); }()
	if ret != 0 {
		return fmt.Errorf("rdma_create_qp failed")
	}
	cb.qp = func() *_Ctype_struct_ibv_qp{ _cgo0 := /*line :686:25*/id; _cgoCheckPointer(_cgo0, nil); return /*line :686:28*/_Cfunc_get_cm_id_qp(_cgo0); }()
	return nil
}

func (cb *RPingCB) freeQP() {
	if cb.qp != nil {
		func() _Ctype_int{ _cgo0 := /*line :692:20*/cb.qp; _cgoCheckPointer(_cgo0, nil); return /*line :692:26*/_Cfunc_ibv_destroy_qp(_cgo0); }()
		cb.qp = nil
	}
	if cb.cq != nil {
		func() _Ctype_int{ _cgo0 := /*line :696:20*/cb.cq; _cgoCheckPointer(_cgo0, nil); return /*line :696:26*/_Cfunc_ibv_destroy_cq(_cgo0); }()
		cb.cq = nil
	}
	if cb.channel != nil {
		func() _Ctype_int{ _cgo0 := /*line :700:30*/cb.channel; _cgoCheckPointer(_cgo0, nil); return /*line :700:41*/_Cfunc_ibv_destroy_comp_channel(_cgo0); }()
		cb.channel = nil
	}
	if cb.pd != nil {
		func() _Ctype_int{ _cgo0 := /*line :704:20*/cb.pd; _cgoCheckPointer(_cgo0, nil); return /*line :704:26*/_Cfunc_ibv_dealloc_pd(_cgo0); }()
		cb.pd = nil
	}
}

// --- Buffer setup ---
func (cb *RPingCB) setupBuffers() error {
	var mr * /*line :711:10*/_Ctype_struct_ibv_mr /*line :711:25*/

	// Register recv buffer
	if ret := func() _Ctype_int{ _cgo0 := /*line :714:29*/cb.pd; _cgoBase1 := /*line :714:51*/&cb.recvBuf; _cgo1 := /*line :714:36*/unsafe.Pointer(_cgoBase1); var _cgo2 _Ctype_size_t = /*line :715:3*/_Ciconst_sizeof_struct_rping_rdma_info /*line :715:34*/; var _cgo3 _Ctype_int = /*line :715:36*/_Ciconst_IBV_ACCESS_LOCAL_WRITE /*line :715:60*/; _cgoBase4 := /*line :715:62*/&mr; _cgo4 := _cgoBase4; _cgoCheckPointer(_cgo0, nil); _cgoCheckPointer(_cgoBase1, 0 == 0); _cgoCheckPointer(_cgoBase4, 0 == 0); return /*line :715:66*/_Cfunc_reg_mr_wrapper(_cgo0, _cgo1, _cgo2, _cgo3, _cgo4); }(); ret != 0 {
		return fmt.Errorf("recv_buf reg_mr failed: %d", ret)
	}
	cb.recvMR = mr

	// Register send buffer
	if ret := func() _Ctype_int{ _cgo0 := /*line :721:29*/cb.pd; _cgoBase1 := /*line :721:51*/&cb.sendBuf; _cgo1 := /*line :721:36*/unsafe.Pointer(_cgoBase1); var _cgo2 _Ctype_size_t = /*line :722:3*/_Ciconst_sizeof_struct_rping_rdma_info /*line :722:34*/; var _cgo3 _Ctype_int = /*line :722:36*/0; _cgoBase4 := /*line :722:39*/&mr; _cgo4 := _cgoBase4; _cgoCheckPointer(_cgo0, nil); _cgoCheckPointer(_cgoBase1, 0 == 0); _cgoCheckPointer(_cgoBase4, 0 == 0); return /*line :722:43*/_Cfunc_reg_mr_wrapper(_cgo0, _cgo1, _cgo2, _cgo3, _cgo4); }(); ret != 0 {
		func() _Ctype_int{ _cgo0 := /*line :723:18*/cb.recvMR; _cgoCheckPointer(_cgo0, nil); return /*line :723:28*/_Cfunc_ibv_dereg_mr(_cgo0); }()
		return fmt.Errorf("send_buf reg_mr failed: %d", ret)
	}
	cb.sendMR = mr

	// Allocate and register rdma buffer
	cb.rdmaBuf = make([]byte, cb.size)
	rdmaAccess :=  /*line :730:16*/_Ctype_int /*line :730:21*/(( /*line :730:22*/_Ciconst_IBV_ACCESS_LOCAL_WRITE /*line :730:45*/) | ( /*line :730:49*/_Ciconst_IBV_ACCESS_REMOTE_READ /*line :730:72*/) | ( /*line :730:76*/_Ciconst_IBV_ACCESS_REMOTE_WRITE /*line :730:100*/))
	if ret := func() _Ctype_int{ _cgo0 := /*line :731:29*/cb.pd; _cgoIndex1 := &/*line :731:52*/cb.rdmaBuf; _cgo1 := /*line :731:36*/unsafe.Pointer(&(*_cgoIndex1)[0]); var _cgo2 _Ctype_size_t = _Ctype_size_t /*line :732:11*/(cb.size); var _cgo3 _Ctype_int = /*line :732:22*/rdmaAccess; _cgoBase4 := /*line :732:34*/&mr; _cgo4 := _cgoBase4; _cgoCheckPointer(_cgo0, nil); _cgoCheckPointer(_cgo1, *_cgoIndex1); _cgoCheckPointer(_cgoBase4, 0 == 0); return /*line :732:38*/_Cfunc_reg_mr_wrapper(_cgo0, _cgo1, _cgo2, _cgo3, _cgo4); }(); ret != 0 {
		func() _Ctype_int{ _cgo0 := /*line :733:18*/cb.sendMR; _cgoCheckPointer(_cgo0, nil); return /*line :733:28*/_Cfunc_ibv_dereg_mr(_cgo0); }()
		func() _Ctype_int{ _cgo0 := /*line :734:18*/cb.recvMR; _cgoCheckPointer(_cgo0, nil); return /*line :734:28*/_Cfunc_ibv_dereg_mr(_cgo0); }()
		return fmt.Errorf("rdma_buf reg_mr failed: %d", ret)
	}
	cb.rdmaMR = mr

	// Client also needs start buffer
	if !cb.server {
		cb.startBuf = make([]byte, cb.size)
		if ret := func() _Ctype_int{ _cgo0 := /*line :742:30*/cb.pd; _cgoIndex1 := &/*line :742:53*/cb.startBuf; _cgo1 := /*line :742:37*/unsafe.Pointer(&(*_cgoIndex1)[0]); var _cgo2 _Ctype_size_t = _Ctype_size_t /*line :743:12*/(cb.size); var _cgo3 _Ctype_int = /*line :743:23*/rdmaAccess; _cgoBase4 := /*line :743:35*/&mr; _cgo4 := _cgoBase4; _cgoCheckPointer(_cgo0, nil); _cgoCheckPointer(_cgo1, *_cgoIndex1); _cgoCheckPointer(_cgoBase4, 0 == 0); return /*line :743:39*/_Cfunc_reg_mr_wrapper(_cgo0, _cgo1, _cgo2, _cgo3, _cgo4); }(); ret != 0 {
			func() _Ctype_int{ _cgo0 := /*line :744:19*/cb.rdmaMR; _cgoCheckPointer(_cgo0, nil); return /*line :744:29*/_Cfunc_ibv_dereg_mr(_cgo0); }()
			func() _Ctype_int{ _cgo0 := /*line :745:19*/cb.sendMR; _cgoCheckPointer(_cgo0, nil); return /*line :745:29*/_Cfunc_ibv_dereg_mr(_cgo0); }()
			func() _Ctype_int{ _cgo0 := /*line :746:19*/cb.recvMR; _cgoCheckPointer(_cgo0, nil); return /*line :746:29*/_Cfunc_ibv_dereg_mr(_cgo0); }()
			return fmt.Errorf("start_buf reg_mr failed: %d", ret)
		}
		cb.startMR = mr
	}

	// Set up work requests
	func() { _cgoBase0 := /*line :753:18*/&cb.rqWr; _cgo0 := _cgoBase0; var _cgo1 *_Ctype_struct_ibv_sge = /*line :753:28*/&cb.recvSGL; var _cgo2 *_Ctype_struct_rping_rdma_info = /*line :753:41*/&cb.recvBuf; var _cgo3 _Ctype_uint32_t = func() _Ctype_uint32_t{ _cgo0 := /*line :753:65*/cb.recvMR; _cgoCheckPointer(_cgo0, nil); return /*line :753:75*/_Cfunc_get_lkey(_cgo0); }(); _cgoCheckPointer(_cgoBase0, 0 == 0); /*line :753:76*/_Cfunc_setup_recv_wr(_cgo0, _cgo1, _cgo2, _cgo3); }()
	func() { _cgoBase0 := /*line :754:18*/&cb.sqWr; _cgo0 := _cgoBase0; var _cgo1 *_Ctype_struct_ibv_sge = /*line :754:28*/&cb.sendSGL; var _cgo2 *_Ctype_struct_rping_rdma_info = /*line :754:41*/&cb.sendBuf; var _cgo3 _Ctype_uint32_t = func() _Ctype_uint32_t{ _cgo0 := /*line :754:65*/cb.sendMR; _cgoCheckPointer(_cgo0, nil); return /*line :754:75*/_Cfunc_get_lkey(_cgo0); }(); _cgoCheckPointer(_cgoBase0, 0 == 0); /*line :754:76*/_Cfunc_setup_send_wr(_cgo0, _cgo1, _cgo2, _cgo3); }()
	func() { _cgoBase0 := /*line :755:18*/&cb.rdmaWr; _cgo0 := _cgoBase0; var _cgo1 *_Ctype_struct_ibv_sge = /*line :755:30*/&cb.rdmaSGL; _cgoIndex2 := &/*line :755:59*/cb.rdmaBuf; _cgo2 := /*line :755:43*/unsafe.Pointer(&(*_cgoIndex2)[0]); var _cgo3 _Ctype_uint32_t = func() _Ctype_uint32_t{ _cgo0 := /*line :755:86*/cb.rdmaMR; _cgoCheckPointer(_cgo0, nil); return /*line :755:96*/_Cfunc_get_lkey(_cgo0); }(); _cgoCheckPointer(_cgoBase0, 0 == 0); _cgoCheckPointer(_cgo2, *_cgoIndex2); /*line :755:97*/_Cfunc_setup_rdma_wr(_cgo0, _cgo1, _cgo2, _cgo3); }()

	runtime.KeepAlive(cb.rdmaBuf)
	if !cb.server {
		runtime.KeepAlive(cb.startBuf)
	}

	return nil
}

func (cb *RPingCB) freeBuffers() {
	if cb.recvMR != nil {
		func() _Ctype_int{ _cgo0 := /*line :767:18*/cb.recvMR; _cgoCheckPointer(_cgo0, nil); return /*line :767:28*/_Cfunc_ibv_dereg_mr(_cgo0); }()
		cb.recvMR = nil
	}
	if cb.sendMR != nil {
		func() _Ctype_int{ _cgo0 := /*line :771:18*/cb.sendMR; _cgoCheckPointer(_cgo0, nil); return /*line :771:28*/_Cfunc_ibv_dereg_mr(_cgo0); }()
		cb.sendMR = nil
	}
	if cb.rdmaMR != nil {
		func() _Ctype_int{ _cgo0 := /*line :775:18*/cb.rdmaMR; _cgoCheckPointer(_cgo0, nil); return /*line :775:28*/_Cfunc_ibv_dereg_mr(_cgo0); }()
		cb.rdmaMR = nil
	}
	cb.rdmaBuf = nil
	if !cb.server && cb.startMR != nil {
		func() _Ctype_int{ _cgo0 := /*line :780:18*/cb.startMR; _cgoCheckPointer(_cgo0, nil); return /*line :780:29*/_Cfunc_ibv_dereg_mr(_cgo0); }()
		cb.startMR = nil
		cb.startBuf = nil
	}
}

// --- Send/Recv helpers ---
func (cb *RPingCB) formatSend(buf unsafe.Pointer, mr * /*line :787:55*/_Ctype_struct_ibv_mr /*line :787:70*/) {
	( /*line :788:2*/_Cfunc_fill_rdma_info /*line :788:17*/)(&cb.sendBuf,  /*line :788:32*/_Ctype_uint64_t /*line :788:42*/(uintptr(buf)), func() _Ctype_uint32_t{ _cgo0 := /*line :788:69*/mr; _cgoCheckPointer(_cgo0, nil); return /*line :788:72*/_Cfunc_get_rkey(_cgo0); }(),  /*line :788:74*/_Ctype_uint32_t /*line :788:84*/(cb.size))
}

func (cb *RPingCB) postRecv() error {
	var badWr * /*line :792:13*/_Ctype_struct_ibv_recv_wr /*line :792:33*/
	ret := func() _Ctype_int{ _cgo0 := /*line :793:25*/cb.qp; _cgoBase1 := /*line :793:32*/&cb.rqWr; _cgo1 := _cgoBase1; _cgoBase2 := /*line :793:42*/&badWr; _cgo2 := _cgoBase2; _cgoCheckPointer(_cgo0, nil); _cgoCheckPointer(_cgoBase1, 0 == 0); _cgoCheckPointer(_cgoBase2, 0 == 0); return /*line :793:49*/_Cfunc_ibv_post_recv(_cgo0, _cgo1, _cgo2); }()
	if ret != 0 {
		return fmt.Errorf("ibv_post_recv failed: %d", ret)
	}
	return nil
}

func (cb *RPingCB) postSend() error {
	var badWr * /*line :801:13*/_Ctype_struct_ibv_send_wr /*line :801:33*/
	ret := func() _Ctype_int{ _cgo0 := /*line :802:25*/cb.qp; _cgoBase1 := /*line :802:32*/&cb.sqWr; _cgo1 := _cgoBase1; _cgoBase2 := /*line :802:42*/&badWr; _cgo2 := _cgoBase2; _cgoCheckPointer(_cgo0, nil); _cgoCheckPointer(_cgoBase1, 0 == 0); _cgoCheckPointer(_cgoBase2, 0 == 0); return /*line :802:49*/_Cfunc_ibv_post_send(_cgo0, _cgo1, _cgo2); }()
	if ret != 0 {
		return fmt.Errorf("ibv_post_send failed: %d", ret)
	}
	return nil
}

func (cb *RPingCB) postRdmaWR() error {
	var badWr * /*line :810:13*/_Ctype_struct_ibv_send_wr /*line :810:33*/
	ret := func() _Ctype_int{ _cgo0 := /*line :811:25*/cb.qp; _cgoBase1 := /*line :811:32*/&cb.rdmaWr; _cgo1 := _cgoBase1; _cgoBase2 := /*line :811:44*/&badWr; _cgo2 := _cgoBase2; _cgoCheckPointer(_cgo0, nil); _cgoCheckPointer(_cgoBase1, 0 == 0); _cgoCheckPointer(_cgoBase2, 0 == 0); return /*line :811:51*/_Cfunc_ibv_post_send(_cgo0, _cgo1, _cgo2); }()
	if ret != 0 {
		return fmt.Errorf("ibv_post_send (rdma) failed: %d", ret)
	}
	return nil
}

// --- Connection management ---
func (cb *RPingCB) accept() error {
	if cb.selfCreateQP {
		ret := func() _Ctype_int{ _cgo0 := /*line :821:27*/cb.qp; _cgo1 := /*line :821:34*/cb.childCMID; _cgoCheckPointer(_cgo0, nil); _cgoCheckPointer(_cgo1, nil); return /*line :821:47*/_Cfunc_self_modify_qp(_cgo0, _cgo1); }()
		if ret != 0 {
			return fmt.Errorf("self_modify_qp failed")
		}
		var connParam  /*line :825:17*/_Ctype_struct_rdma_conn_param /*line :825:41*/
		func() { _cgoBase0 := /*line :826:21*/&connParam; _cgo0 := _cgoBase0; var _cgo1 _Ctype_int = _Ctype_int /*line :826:38*/(func() _Ctype_uint32_t{ _cgo0 := /*line :826:52*/cb.qp; _cgoCheckPointer(_cgo0, nil); return /*line :826:58*/_Cfunc_get_qp_num(_cgo0); }()); var _cgo2 _Ctype_int = /*line :826:61*/1; _cgoCheckPointer(_cgoBase0, 0 == 0); /*line :826:63*/_Cfunc_init_conn_param(_cgo0, _cgo1, _cgo2); }()
		ret = func() _Ctype_int{ _cgo0 := /*line :827:23*/cb.childCMID; _cgoBase1 := /*line :827:37*/&connParam; _cgo1 := _cgoBase1; _cgoCheckPointer(_cgo0, nil); _cgoCheckPointer(_cgoBase1, 0 == 0); return /*line :827:48*/_Cfunc_rdma_accept(_cgo0, _cgo1); }()
		if ret != 0 {
			return fmt.Errorf("rdma_accept failed")
		}
	} else {
		ret := func() _Ctype_int{ _cgo0 := /*line :832:24*/cb.childCMID; var _cgo1 *_Ctype_struct_rdma_conn_param = /*line :832:38*/nil; _cgoCheckPointer(_cgo0, nil); return /*line :832:42*/_Cfunc_rdma_accept(_cgo0, _cgo1); }()
		if ret != 0 {
			return fmt.Errorf("rdma_accept failed")
		}
	}

	s := cb.waitState(StateConnected, StateError)
	if s != StateConnected {
		return fmt.Errorf("wait for CONNECTED state %s", s)
	}
	return nil
}

func (cb *RPingCB) disconnect(id * /*line :845:35*/_Ctype_struct_ibv_cm_id /*line :845:53*/) error {
	if cb.selfCreateQP {
		var qpAttr  /*line :847:14*/_Ctype_struct_ibv_qp_attr /*line :847:34*/
		func() _cgo_unsafe.Pointer{ _cgoBase0 := /*line :848:27*/&qpAttr; _cgo0 := /*line :848:12*/unsafe.Pointer(_cgoBase0); var _cgo1 _Ctype_int = /*line :848:37*/0; var _cgo2 _Ctype_size_t = /*line :848:40*/_Ciconst_sizeof_struct_ibv_qp_attr /*line :848:67*/; _cgoCheckPointer(_cgoBase0, 0 == 0); return /*line :848:68*/_Cfunc_memset(_cgo0, _cgo1, _cgo2); }()
		qpAttr.qp_state = ( /*line :849:21*/_Ciconst_IBV_QPS_ERR /*line :849:33*/)
		func() _Ctype_int{ _cgo0 := /*line :850:19*/cb.qp; var _cgo1 *_Ctype_struct_ibv_qp_attr = /*line :850:26*/&qpAttr; var _cgo2 _Ctype_int = /*line :850:35*/_Ciconst_IBV_QP_STATE /*line :850:49*/; _cgoCheckPointer(_cgo0, nil); return /*line :850:50*/_Cfunc_ibv_modify_qp(_cgo0, _cgo1, _cgo2); }()
	}
	ret := func() _Ctype_int{ _cgo0 := /*line :852:27*/id; _cgoCheckPointer(_cgo0, nil); return /*line :852:30*/_Cfunc_rdma_disconnect(_cgo0); }()
	if ret != 0 {
		return fmt.Errorf("rdma_disconnect failed")
	}
	return nil
}

func (cb *RPingCB) connectClient() error {
	var connParam  /*line :860:16*/_Ctype_struct_rdma_conn_param /*line :860:40*/
	qpNum :=  /*line :861:11*/_Ctype_int /*line :861:16*/(0)
	if cb.selfCreateQP && cb.qp != nil {
		qpNum =  /*line :863:11*/_Ctype_int /*line :863:16*/(func() _Ctype_uint32_t{ _cgo0 := /*line :863:30*/cb.qp; _cgoCheckPointer(_cgo0, nil); return /*line :863:36*/_Cfunc_get_qp_num(_cgo0); }())
	}
	selfQP :=  /*line :865:12*/_Ctype_int /*line :865:17*/(0)
	if cb.selfCreateQP {
		selfQP = 1
	}
	func() { _cgoBase0 := /*line :869:20*/&connParam; _cgo0 := _cgoBase0; var _cgo1 _Ctype_int = /*line :869:32*/qpNum; var _cgo2 _Ctype_int = /*line :869:39*/selfQP; _cgoCheckPointer(_cgoBase0, 0 == 0); /*line :869:46*/_Cfunc_init_conn_param(_cgo0, _cgo1, _cgo2); }()

	ret := func() _Ctype_int{ _cgo0 := /*line :871:24*/cb.cmID; _cgoBase1 := /*line :871:33*/&connParam; _cgo1 := _cgoBase1; _cgoCheckPointer(_cgo0, nil); _cgoCheckPointer(_cgoBase1, 0 == 0); return /*line :871:44*/_Cfunc_rdma_connect(_cgo0, _cgo1); }()
	if ret != 0 {
		return fmt.Errorf("rdma_connect failed")
	}

	s := cb.waitState(StateConnected, StateError)
	if s != StateConnected {
		return fmt.Errorf("wait for CONNECTED state %s", s)
	}

	if cb.selfCreateQP {
		ret = func() _Ctype_int{ _cgo0 := /*line :882:26*/cb.qp; _cgo1 := /*line :882:33*/cb.cmID; _cgoCheckPointer(_cgo0, nil); _cgoCheckPointer(_cgo1, nil); return /*line :882:41*/_Cfunc_self_modify_qp(_cgo0, _cgo1); }()
		if ret != 0 {
			return fmt.Errorf("self_modify_qp failed")
		}
		ret = func() _Ctype_int{ _cgo0 := /*line :886:26*/cb.cmID; _cgoCheckPointer(_cgo0, nil); return /*line :886:34*/_Cfunc_rdma_establish(_cgo0); }()
		if ret != 0 {
			return fmt.Errorf("rdma_establish failed")
		}
	}

	return nil
}

func (cb *RPingCB) bindClient() error {
	( /*line :896:2*/_Cfunc_set_sockaddr_port /*line :896:20*/)((* /*line :896:24*/_Ctype_struct_sockaddr /*line :896:41*/)(unsafe.Pointer(&cb.sin)),  /*line :896:69*/_Ctype_ushort /*line :896:77*/(cb.port))

	var ret  /*line :898:10*/_Ctype_int /*line :898:15*/
	if cb.ssource.ss_family != 0 {
		ret = func() _Ctype_int{ _cgo0 := /*line :900:29*/cb.cmID; var _cgo1 *_Ctype_struct_sockaddr = /*line :901:4*/(*_Ctype_struct_sockaddr /*line :901:23*/)(unsafe.Pointer(&cb.ssource)); var _cgo2 *_Ctype_struct_sockaddr = /*line :902:4*/(*_Ctype_struct_sockaddr /*line :902:23*/)(unsafe.Pointer(&cb.sin)); var _cgo3 _Ctype_int = /*line :902:51*/2000; _cgoCheckPointer(_cgo0, nil); return /*line :902:56*/_Cfunc_rdma_resolve_addr(_cgo0, _cgo1, _cgo2, _cgo3); }()
	} else {
		ret = func() _Ctype_int{ _cgo0 := /*line :904:29*/cb.cmID; var _cgo1 *_Ctype_struct_sockaddr = /*line :904:38*/nil; var _cgo2 *_Ctype_struct_sockaddr = /*line :905:4*/(*_Ctype_struct_sockaddr /*line :905:23*/)(unsafe.Pointer(&cb.sin)); var _cgo3 _Ctype_int = /*line :905:51*/2000; _cgoCheckPointer(_cgo0, nil); return /*line :905:56*/_Cfunc_rdma_resolve_addr(_cgo0, _cgo1, _cgo2, _cgo3); }()
	}
	if ret != 0 {
		return fmt.Errorf("rdma_resolve_addr failed")
	}

	s := cb.waitState(StateRouteResolved, StateError)
	if s != StateRouteResolved {
		return fmt.Errorf("waiting for addr/route resolution state %s", s)
	}
	return nil
}

func (cb *RPingCB) bindServer() error {
	( /*line :919:2*/_Cfunc_set_sockaddr_port /*line :919:20*/)((* /*line :919:24*/_Ctype_struct_sockaddr /*line :919:41*/)(unsafe.Pointer(&cb.sin)),  /*line :919:69*/_Ctype_ushort /*line :919:77*/(cb.port))

	ret := func() _Ctype_int{ _cgo0 := /*line :921:26*/cb.cmID; var _cgo1 *_Ctype_struct_sockaddr = /*line :921:35*/(*_Ctype_struct_sockaddr /*line :921:54*/)(unsafe.Pointer(&cb.sin)); _cgoCheckPointer(_cgo0, nil); return /*line :921:81*/_Cfunc_rdma_bind_addr(_cgo0, _cgo1); }()
	if ret != 0 {
		return fmt.Errorf("rdma_bind_addr failed")
	}

	ret = func() _Ctype_int{ _cgo0 := /*line :926:22*/cb.cmID; var _cgo1 _Ctype_int = /*line :926:31*/3; _cgoCheckPointer(_cgo0, nil); return /*line :926:33*/_Cfunc_rdma_listen(_cgo0, _cgo1); }()
	if ret != 0 {
		return fmt.Errorf("rdma_listen failed")
	}
	return nil
}

func (cb *RPingCB) getAddrString() string {
	var addrStr [( /*line :934:15*/_Ciconst_INET6_ADDRSTRLEN /*line :934:32*/)]byte
	( /*line :935:2*/_Cfunc_getnameinfo_wrapper /*line :935:22*/)(
		(* /*line :936:5*/_Ctype_struct_sockaddr /*line :936:22*/)(unsafe.Pointer(&cb.sin)),
		 /*line :937:3*/_Ctype_socklen_t /*line :937:14*/(( /*line :937:15*/_Ciconst_sizeof_struct_sockaddr_storage /*line :937:46*/)),
		(* /*line :938:5*/_Ctype_char /*line :938:11*/)(unsafe.Pointer(&addrStr[0])),
		( /*line :939:3*/_Ciconst_INET6_ADDRSTRLEN /*line :939:20*/))
	return ( /*line :940:9*/_Cfunc_GoString /*line :940:18*/)((* /*line :940:22*/_Ctype_char /*line :940:28*/)(unsafe.Pointer(&addrStr[0])))
}

// --- CM thread ---
func cmThread(cb *RPingCB, stopCh chan struct{}) {
	defer close(cb.cmDone)

	var pfds [2] /*line :947:14*/_Ctype_struct_pollfd /*line :947:29*/
	pfds[0].fd = cb.eventfd
	pfds[0].events = ( /*line :949:19*/_Ciconst_POLLIN /*line :949:26*/)
	pfds[1].fd = ( /*line :950:15*/_Cfunc_get_channel_fd /*line :950:30*/)(cb.cmChannel)
	pfds[1].events = ( /*line :951:19*/_Ciconst_POLLIN /*line :951:26*/)

	for {
		ret := ( /*line :954:10*/_Cfunc_poll_wrapper /*line :954:23*/)(&pfds[0], 2, -1)
		if ret < 0 {
			fmt.Fprintf(os.Stderr, "poll failed: %v\n", syscall.Errno(-ret))
			return
		}
		if ret == 0 {
			continue
		}

		if pfds[0].revents&( /*line :963:22*/_Ciconst_POLLIN /*line :963:29*/) != 0 {
			return
		}

		if pfds[1].revents&( /*line :967:22*/_Ciconst_POLLIN /*line :967:29*/) != 0 {
			var event * /*line :968:15*/_Ctype_struct_rdma_cm_event /*line :968:37*/
			ret := func() _Ctype_int{ var _cgo0 *_Ctype_struct_rdma_event_channel = /*line :969:34*/cb.cmChannel; _cgoBase1 := /*line :969:48*/&event; _cgo1 := _cgoBase1; _cgoCheckPointer(_cgoBase1, 0 == 0); return /*line :969:55*/_Cfunc_get_cm_event_wrapper(_cgo0, _cgo1); }()
			if ret != 0 {
				fmt.Fprintf(os.Stderr, "rdma_get_cm_event: %v\n", syscall.Errno(-ret))
				return
			}
			cmaID := func() *_Ctype_struct_rdma_cm_id{ _cgo0 := /*line :974:28*/event; _cgoCheckPointer(_cgo0, nil); return /*line :974:34*/_Cfunc_get_event_id(_cgo0); }()
			handlerRet := cb.cmaEventHandler(cmaID, event)
			func() _Ctype_int{ _cgo0 := /*line :976:24*/event; _cgoCheckPointer(_cgo0, nil); return /*line :976:30*/_Cfunc_rdma_ack_cm_event(_cgo0); }()
			if handlerRet != 0 {
				return
			}
		}

		select {
		case <-stopCh:
			return
		default:
		}
	}
}

// --- CQ thread ---
func cqThread(cb *RPingCB, stopCh chan struct{}) {
	defer close(cb.cqDone)

	for {
		select {
		case <-stopCh:
			return
		default:
		}

		var evCQ * /*line :1001:13*/_Ctype_struct_ibv_cq /*line :1001:28*/
		var evCtx unsafe.Pointer

		ret := func() _Ctype_int{ _cgo0 := /*line :1004:33*/cb.channel; _cgoBase1 := /*line :1004:45*/&evCQ; _cgo1 := _cgoBase1; _cgoBase2 := /*line :1004:52*/&evCtx; _cgo2 := _cgoBase2; _cgoCheckPointer(_cgo0, nil); _cgoCheckPointer(_cgoBase1, 0 == 0); _cgoCheckPointer(_cgoBase2, 0 == 0); return /*line :1004:59*/_Cfunc_get_cq_event_wrapper(_cgo0, _cgo1, _cgo2); }()
		if ret != 0 {
			fmt.Fprintf(os.Stderr, "Failed to get cq event!\n")
			return
		}
		if evCQ != cb.cq {
			fmt.Fprintf(os.Stderr, "Unknown CQ!\n")
			return
		}

		if ret = func() _Ctype_int{ _cgo0 := /*line :1014:32*/cb.cq; var _cgo1 _Ctype_int = /*line :1014:39*/0; _cgoCheckPointer(_cgo0, nil); return /*line :1014:41*/_Cfunc_ibv_req_notify_cq(_cgo0, _cgo1); }(); ret != 0 {
			fmt.Fprintf(os.Stderr, "Failed to set notify!\n")
			return
		}

		handlerRet := cb.cqEventHandler()
		func() { _cgo0 := /*line :1020:23*/cb.cq; var _cgo1 _Ctype_uint = /*line :1020:30*/1; _cgoCheckPointer(_cgo0, nil); /*line :1020:32*/_Cfunc_ibv_ack_cq_events(_cgo0, _cgo1); }()
		if handlerRet != 0 {
			fmt.Fprintf(os.Stderr, "CQ event handler returned %d\n", handlerRet)
			return
		}
	}
}

// --- Server ping/pong loop ---
func testServer(cb *RPingCB) int {
	for {
		// Wait for client's Start STAG/TO/Len
		s := cb.waitState(StateRDMAReadAdv, StateDisconnected, StateError)
		if s != StateRDMAReadAdv {
			if s == StateDisconnected {
				return 0
			}
			fmt.Fprintf(os.Stderr, "wait for RDMA_READ_ADV state %s\n", s)
			return -1
		}

		// Issue RDMA Read
		func() { _cgoBase0 := /*line :1042:22*/&cb.rdmaWr; _cgo0 := _cgoBase0; var _cgo1 _Ctype_uint32_t = _Ctype_uint32_t /*line :1043:14*/(cb.remoteRkey); var _cgo2 _Ctype_uint64_t = _Ctype_uint64_t /*line :1043:41*/(cb.remoteAddr); var _cgo3 _Ctype_uint32_t = _Ctype_uint32_t /*line :1043:68*/(cb.remoteLen); _cgoCheckPointer(_cgoBase0, 0 == 0); /*line :1043:83*/_Cfunc_set_rdma_read_wr(_cgo0, _cgo1, _cgo2, _cgo3); }()
		if err := cb.postRdmaWR(); err != nil {
			fmt.Fprintf(os.Stderr, "post rdma read error: %v\n", err)
			break
		}

		// Wait for read completion
		s = cb.waitState(StateRDMAReadComplete, StateDisconnected, StateError)
		if s != StateRDMAReadComplete {
			fmt.Fprintf(os.Stderr, "wait for RDMA_READ_COMPLETE state %s\n", s)
			return -1
		}

		// Display data
		if cb.verbose > 0 {
			rdmaStr := ( /*line :1058:15*/_Cfunc_GoStringN /*line :1058:25*/)((* /*line :1058:29*/_Ctype_char /*line :1058:35*/)(unsafe.Pointer(&cb.rdmaBuf[0])),  /*line :1058:70*/_Ctype_int /*line :1058:75*/(cb.size))
			fmt.Printf("server ping data: %s\n", rdmaStr)
		}

		// Tell client to continue
		if err := cb.postSend(); err != nil {
			fmt.Fprintf(os.Stderr, "post send error: %v\n", err)
			break
		}

		// Wait for client's RDMA STAG/TO/Len
		s = cb.waitState(StateRDMAWriteAdv, StateDisconnected, StateError)
		if s != StateRDMAWriteAdv {
			fmt.Fprintf(os.Stderr, "wait for RDMA_WRITE_ADV state %s\n", s)
			return -1
		}

		// RDMA Write echo data
		writeLen := uint32(( /*line :1076:22*/_Cfunc_get_rdma_buf_strlen /*line :1076:42*/)((* /*line :1076:46*/_Ctype_char /*line :1076:52*/)(unsafe.Pointer(&cb.rdmaBuf[0]))))
		func() { _cgoBase0 := /*line :1077:23*/&cb.rdmaWr; _cgo0 := _cgoBase0; var _cgo1 _Ctype_uint32_t = _Ctype_uint32_t /*line :1078:14*/(cb.remoteRkey); var _cgo2 _Ctype_uint64_t = _Ctype_uint64_t /*line :1078:41*/(cb.remoteAddr); var _cgo3 _Ctype_uint32_t = _Ctype_uint32_t /*line :1078:68*/(writeLen); _cgoCheckPointer(_cgoBase0, 0 == 0); /*line :1078:79*/_Cfunc_set_rdma_write_wr(_cgo0, _cgo1, _cgo2, _cgo3); }()
		if err := cb.postRdmaWR(); err != nil {
			fmt.Fprintf(os.Stderr, "post rdma write error: %v\n", err)
			break
		}

		// Wait for write completion
		s = cb.waitState(StateRDMAWriteComplete, StateDisconnected, StateError)
		if s != StateRDMAWriteComplete {
			fmt.Fprintf(os.Stderr, "wait for RDMA_WRITE_COMPLETE state %s\n", s)
			return -1
		}

		// Tell client to begin again
		if err := cb.postSend(); err != nil {
			fmt.Fprintf(os.Stderr, "post send error: %v\n", err)
			break
		}
	}

	if cb.getState() == StateDisconnected {
		return 0
	}
	return -1
}

// --- Client ping/pong loop ---
func testClient(cb *RPingCB) int {
	var rttMin, rttMax, rttSum float64
	packetsSent := 0
	packetsReceived := 0
	startChar := byte(65)

	totalStart := time.Now()

	for ping := 0; cb.count == 0 || ping < cb.count; ping++ {
		cb.setState(StateRDMAReadAdv)
		packetsSent++

		// Fill buffer with ascii text
		cc := fmt.Sprintf(rpingMsgFmt, ping)
		copy(cb.startBuf, []byte(cc))
		c := startChar
		for i := len(cc); i < cb.size; i++ {
			cb.startBuf[i] = c
			c++
			if c > 122 {
				c = 65
			}
		}
		startChar++
		if startChar > 122 {
			startChar = 65
		}
		cb.startBuf[cb.size-1] = 0

		pingStart := time.Now()

		// Send source rkey/addr/len to server
		cb.formatSend(unsafe.Pointer(&cb.startBuf[0]), cb.startMR)
		if err := cb.postSend(); err != nil {
			fmt.Fprintf(os.Stderr, "post send error: %v\n", err)
			break
		}

		// Wait for server to ACK
		s := cb.waitState(StateRDMAWriteAdv, StateDisconnected, StateError)
		if s != StateRDMAWriteAdv {
			fmt.Fprintf(os.Stderr, "wait for RDMA_WRITE_ADV state %s\n", s)
			return -1
		}

		// Send sink rkey/addr/len to server
		cb.formatSend(unsafe.Pointer(&cb.rdmaBuf[0]), cb.rdmaMR)
		if err := cb.postSend(); err != nil {
			fmt.Fprintf(os.Stderr, "post send error: %v\n", err)
			break
		}

		// Wait for RDMA Write complete
		s = cb.waitState(StateRDMAWriteComplete, StateDisconnected, StateError)
		if s != StateRDMAWriteComplete {
			fmt.Fprintf(os.Stderr, "wait for RDMA_WRITE_COMPLETE state %s\n", s)
			return -1
		}

		// Validate data
		if cb.validate {
			for i := 0; i < cb.size; i++ {
				if cb.startBuf[i] != cb.rdmaBuf[i] {
					fmt.Fprintf(os.Stderr, "data mismatch at offset %d!\n", i)
					return -1
				}
			}
		}

		if cb.verbose > 0 {
			rdmaStr := ( /*line :1175:15*/_Cfunc_GoStringN /*line :1175:25*/)((* /*line :1175:29*/_Ctype_char /*line :1175:35*/)(unsafe.Pointer(&cb.rdmaBuf[0])),  /*line :1175:70*/_Ctype_int /*line :1175:75*/(cb.size))
			fmt.Printf("ping data: %s\n", rdmaStr)
		}

		pingEnd := time.Now()
		elapsedMs := float64(pingEnd.Sub(pingStart)) / float64(time.Millisecond)

		addrStr := cb.getAddrString()
		fmt.Printf("rdma-ping-%d: %s request took %.3f ms\n", ping, addrStr, elapsedMs)

		packetsReceived++
		if packetsReceived == 1 {
			rttMin = elapsedMs
			rttMax = elapsedMs
		} else {
			if elapsedMs < rttMin {
				rttMin = elapsedMs
			}
			if elapsedMs > rttMax {
				rttMax = elapsedMs
			}
		}
		rttSum += elapsedMs
	}

	totalEnd := time.Now()
	totalTimeMs := float64(totalEnd.Sub(totalStart)) / float64(time.Millisecond)

	fmt.Printf("\n--- rping statistics ---\n")
	packetLoss := 0
	if packetsSent > 0 {
		packetLoss = (packetsSent - packetsReceived) * 100 / packetsSent
	}
	fmt.Printf("%d packets transmitted, %d received, %d%% packet loss, time %.0f ms\n",
		packetsSent, packetsReceived, packetLoss, totalTimeMs)
	if packetsReceived > 0 {
		fmt.Printf("rtt min/avg/max = %.3f/%.3f/%.3f ms\n",
			rttMin, rttSum/float64(packetsReceived), rttMax)
	}

	if cb.getState() == StateDisconnected {
		return 0
	}
	return 0
}

// --- Run client ---
func runClient(cb *RPingCB) int {
	if err := cb.bindClient(); err != nil {
		fmt.Fprintf(os.Stderr, "bind_client failed: %v\n", err)
		return -1
	}

	if err := cb.setupQP(cb.cmID); err != nil {
		fmt.Fprintf(os.Stderr, "setup_qp failed: %v\n", err)
		return -1
	}

	if err := cb.setupBuffers(); err != nil {
		fmt.Fprintf(os.Stderr, "rping_setup_buffers failed: %v\n", err)
		cb.freeQP()
		return -1
	}

	if err := cb.postRecv(); err != nil {
		fmt.Fprintf(os.Stderr, "ibv_post_recv failed: %v\n", err)
		cb.freeBuffers()
		cb.freeQP()
		return -1
	}

	cqStopCh := make(chan struct{})
	cb.cqDone = make(chan struct{})
	go cqThread(cb, cqStopCh)

	if err := cb.connectClient(); err != nil {
		fmt.Fprintf(os.Stderr, "connect error: %v\n", err)
		close(cqStopCh)
		<-cb.cqDone
		cb.freeBuffers()
		cb.freeQP()
		return -1
	}

	ret := testClient(cb)

	cb.disconnect(cb.cmID)
	close(cqStopCh)
	<-cb.cqDone
	cb.freeBuffers()
	cb.freeQP()
	return ret
}

// --- Run server (single connection) ---
func runServer(cb *RPingCB) int {
	if err := cb.bindServer(); err != nil {
		fmt.Fprintf(os.Stderr, "bind_server failed: %v\n", err)
		return -1
	}

	s := cb.waitState(StateConnectRequest, StateError)
	if s != StateConnectRequest {
		fmt.Fprintf(os.Stderr, "wait for CONNECT_REQUEST state %s\n", s)
		return -1
	}

	if err := cb.setupQP(cb.childCMID); err != nil {
		fmt.Fprintf(os.Stderr, "setup_qp failed: %v\n", err)
		return -1
	}

	if err := cb.setupBuffers(); err != nil {
		fmt.Fprintf(os.Stderr, "rping_setup_buffers failed: %v\n", err)
		cb.freeQP()
		return -1
	}

	if err := cb.postRecv(); err != nil {
		fmt.Fprintf(os.Stderr, "ibv_post_recv failed: %v\n", err)
		cb.freeBuffers()
		cb.freeQP()
		return -1
	}

	cqStopCh := make(chan struct{})
	cb.cqDone = make(chan struct{})
	go cqThread(cb, cqStopCh)

	if err := cb.accept(); err != nil {
		fmt.Fprintf(os.Stderr, "connect error: %v\n", err)
		close(cqStopCh)
		<-cb.cqDone
		cb.freeBuffers()
		cb.freeQP()
		return -1
	}

	ret := testServer(cb)

	cb.disconnect(cb.childCMID)
	close(cqStopCh)
	<-cb.cqDone
	func() _Ctype_int{ _cgo0 := /*line :1318:20*/cb.childCMID; _cgoCheckPointer(_cgo0, nil); return /*line :1318:33*/_Cfunc_rdma_destroy_id(_cgo0); }()
	cb.freeBuffers()
	cb.freeQP()
	return ret
}

// --- Persistent server ---
func persistentServerThread(cb *RPingCB) {
	if err := cb.setupQP(cb.childCMID); err != nil {
		fmt.Fprintf(os.Stderr, "setup_qp failed: %v\n", err)
		return
	}

	if err := cb.setupBuffers(); err != nil {
		fmt.Fprintf(os.Stderr, "rping_setup_buffers failed: %v\n", err)
		cb.freeQP()
		return
	}

	if err := cb.postRecv(); err != nil {
		fmt.Fprintf(os.Stderr, "ibv_post_recv failed: %v\n", err)
		cb.freeBuffers()
		cb.freeQP()
		return
	}

	cqStopCh := make(chan struct{})
	cb.cqDone = make(chan struct{})
	go cqThread(cb, cqStopCh)

	if err := cb.accept(); err != nil {
		fmt.Fprintf(os.Stderr, "connect error: %v\n", err)
		close(cqStopCh)
		<-cb.cqDone
		cb.freeBuffers()
		cb.freeQP()
		return
	}

	testServer(cb)
	cb.disconnect(cb.childCMID)
	close(cqStopCh)
	<-cb.cqDone
	cb.freeBuffers()
	cb.freeQP()
	func() _Ctype_int{ _cgo0 := /*line :1363:20*/cb.childCMID; _cgoCheckPointer(_cgo0, nil); return /*line :1363:33*/_Cfunc_rdma_destroy_id(_cgo0); }()
}

func cloneCB(listeningCB *RPingCB) *RPingCB {
	cb := newRPingCB()
	cb.server = true
	cb.mu.Lock()
	cb.state = StateConnectRequest
	cb.mu.Unlock()
	cb.childCMID = listeningCB.childCMID
	cb.sin = listeningCB.sin
	cb.ssource = listeningCB.ssource
	cb.port = listeningCB.port
	cb.verbose = listeningCB.verbose
	cb.selfCreateQP = listeningCB.selfCreateQP
	cb.count = listeningCB.count
	cb.size = listeningCB.size
	cb.validate = listeningCB.validate
	cb.cmChannel = listeningCB.cmChannel
	cb.cmID = listeningCB.cmID
	cb.eventfd = listeningCB.eventfd
	return cb
}

func runPersistentServer(listeningCB *RPingCB) int {
	if err := listeningCB.bindServer(); err != nil {
		fmt.Fprintf(os.Stderr, "bind_server failed: %v\n", err)
		return -1
	}

	for {
		s := listeningCB.waitState(StateConnectRequest, StateError)
		if s != StateConnectRequest {
			fmt.Fprintf(os.Stderr, "wait for CONNECT_REQUEST state %s\n", s)
			return -1
		}

		cb := cloneCB(listeningCB)

		// Reset listening CB state for next connection
		listeningCB.setState(StateIdle)

		go persistentServerThread(cb)
	}
}

// --- Main ---
func main() {
	serverMode := flag.Bool("s", false, "server side")
	clientMode := flag.Bool("c", false, "client side")
	addr := flag.String("a", "", "address")
	srcAddr := flag.String("I", "", "source address to bind to for client")
	port := flag.Int("p", defaultPort, "port")
	size := flag.Int("S", 64, "ping data size")
	count := flag.Int("C", 0, "ping count times (0 = infinite)")
	verbose := flag.Int("v", 0, "display ping data to stdout")
	validate := flag.Bool("V", false, "validate ping data")
	_ = flag.Bool("d", false, "debug printfs")
	persistent := flag.Bool("P", false, "persistent server mode allowing multiple connections")
	selfCreateQP := flag.Bool("q", false, "use self-created, self-modified QP")

	flag.Usage = func() {
		fmt.Fprintf(os.Stderr, "rping -s [-vVd] [-S size] [-C count] [-a addr] [-p port]\n")
		fmt.Fprintf(os.Stderr, "rping -c [-vVd] [-S size] [-C count] [-I addr] -a addr [-p port]\n")
		fmt.Fprintf(os.Stderr, "\t-c\t\tclient side\n")
		fmt.Fprintf(os.Stderr, "\t-I\t\tSource address to bind to for client.\n")
		fmt.Fprintf(os.Stderr, "\t-s\t\tserver side.  To bind to any address with IPv6 use -a ::0\n")
		fmt.Fprintf(os.Stderr, "\t-v\t\tdisplay ping data to stdout\n")
		fmt.Fprintf(os.Stderr, "\t-V\t\tvalidate ping data\n")
		fmt.Fprintf(os.Stderr, "\t-d\t\tdebug printfs\n")
		fmt.Fprintf(os.Stderr, "\t-S size \tping data size\n")
		fmt.Fprintf(os.Stderr, "\t-C count\tping count times\n")
		fmt.Fprintf(os.Stderr, "\t-a addr\t\taddress\n")
		fmt.Fprintf(os.Stderr, "\t-p port\t\tport\n")
		fmt.Fprintf(os.Stderr, "\t-P\t\tpersistent server mode allowing multiple connections\n")
		fmt.Fprintf(os.Stderr, "\t-q\t\tuse self-created, self-modified QP\n")
	}
	flag.Parse()

	if !*serverMode && !*clientMode {
		flag.Usage()
		os.Exit(1)
	}

	if *size < rpingMinBufSize || *size > rpingBufSize-1 {
		fmt.Fprintf(os.Stderr, "Invalid size %d (valid range is %d to %d)\n",
			*size, rpingMinBufSize, rpingBufSize)
		os.Exit(1)
	}

	if *count < 0 {
		fmt.Fprintf(os.Stderr, "Invalid count %d\n", *count)
		os.Exit(1)
	}

	cb := newRPingCB()
	cb.server = *serverMode
	cb.size = *size
	cb.count = *count
	cb.verbose = *verbose
	cb.validate = *validate
	cb.selfCreateQP = *selfCreateQP
	cb.port = uint16(( /*line :1465:19*/_Cfunc_go_htobe16 /*line :1465:30*/)( /*line :1465:32*/_Ctype_ushort /*line :1465:40*/(*port)))

	if *addr != "" {
		sin, err := resolveAddr(*addr)
		if err != nil {
			fmt.Fprintf(os.Stderr, "Failed to resolve address %s: %v\n", *addr, err)
			os.Exit(1)
		}
		cb.sin = sin
	} else {
		cb.sin.ss_family = ( /*line :1475:22*/_Ciconst_PF_INET /*line :1475:30*/)
	}

	if *srcAddr != "" {
		ssource, err := resolveAddr(*srcAddr)
		if err != nil {
			fmt.Fprintf(os.Stderr, "Failed to resolve source address %s: %v\n", *srcAddr, err)
			os.Exit(1)
		}
		cb.ssource = ssource
	}

	// Create eventfd
	cb.eventfd = ( /*line :1488:15*/_Cfunc_eventfd /*line :1488:23*/)(0, ( /*line :1488:28*/_Ciconst_EFD_NONBLOCK /*line :1488:41*/))
	if cb.eventfd == -1 {
		fmt.Fprintf(os.Stderr, "Could not create event FD\n")
		os.Exit(1)
	}

	// Create RDMA CM event channel
	var cmChannel * /*line :1495:17*/_Ctype_struct_rdma_event_channel /*line :1495:44*/
	if ret := func() _Ctype_int{ _cgoBase0 := /*line :1496:43*/&cmChannel; _cgo0 := _cgoBase0; _cgoCheckPointer(_cgoBase0, 0 == 0); return /*line :1496:54*/_Cfunc_create_event_channel_wrapper(_cgo0); }(); ret != 0 {
		fmt.Fprintf(os.Stderr, "Failed to create event channel: %v\n", syscall.Errno(ret))
		os.Exit(1)
	}
	cb.cmChannel = cmChannel

	// Create RDMA CM ID
	ret := func() _Ctype_int{ var _cgo0 *_Ctype_struct_rdma_event_channel = /*line :1503:26*/cb.cmChannel; _cgoBase1 := /*line :1503:40*/&cb.cmID; _cgo1 := _cgoBase1; var _cgo2 _cgo_unsafe.Pointer = /*line :1503:50*/nil; var _cgo3 uint32 = /*line :1503:55*/_Ciconst_RDMA_PS_TCP /*line :1503:68*/; _cgoCheckPointer(_cgoBase1, 0 == 0); return /*line :1503:69*/_Cfunc_rdma_create_id(_cgo0, _cgo1, _cgo2, _cgo3); }()
	if ret != 0 {
		fmt.Fprintf(os.Stderr, "rdma_create_id failed\n")
		os.Exit(1)
	}

	// Start CM event thread
	cmStopCh := make(chan struct{})
	cb.cmDone = make(chan struct{})
	go cmThread(cb, cmStopCh)

	// Run
	var result int
	if cb.server {
		if *persistent {
			result = runPersistentServer(cb)
		} else {
			result = runServer(cb)
		}
	} else {
		result = runClient(cb)
	}

	// Cleanup
	func() _Ctype_int{ _cgo0 := /*line :1527:20*/cb.cmID; _cgoCheckPointer(_cgo0, nil); return /*line :1527:28*/_Cfunc_rdma_destroy_id(_cgo0); }()

	var efdw  /*line :1529:11*/_Ctype_uint64_t /*line :1529:21*/ = 1
	func() _Ctype_ssize_t{ var _cgo0 _Ctype_int = /*line :1530:10*/cb.eventfd; _cgoBase1 := /*line :1530:37*/&efdw; _cgo1 := /*line :1530:22*/unsafe.Pointer(_cgoBase1); var _cgo2 _Ctype_size_t = /*line :1530:45*/_Ciconst_sizeof_uint64_t /*line :1530:62*/; _cgoCheckPointer(_cgoBase1, 0 == 0); return /*line :1530:63*/_Cfunc_write(_cgo0, _cgo1, _cgo2); }()

	<-cb.cmDone
	( /*line :1533:2*/_Cfunc_rdma_destroy_event_channel /*line :1533:29*/)(cb.cmChannel)
	( /*line :1534:2*/_Cfunc_close /*line :1534:8*/)(cb.eventfd)

	os.Exit(result)
}

// netAddrFromSin converts sin to a display string (unused but kept for reference)
func _netAddrFromSin(sin * /*line :1540:27*/_Ctype_struct_sockaddr_storage /*line :1540:52*/) string {
	family := sin.ss_family
	if family == ( /*line :1542:15*/_Ciconst_AF_INET /*line :1542:23*/) {
		sin4 := (* /*line :1543:13*/_Ctype_struct_sockaddr_in /*line :1543:33*/)(unsafe.Pointer(sin))
		ip := func() []byte{ _cgoBase0 := /*line :1544:34*/&sin4.sin_addr; _cgo0 := /*line :1544:19*/unsafe.Pointer(_cgoBase0); var _cgo1 _Ctype_int = /*line :1544:51*/4; _cgoCheckPointer(_cgoBase0, 0 == 0); return /*line :1544:53*/_Cfunc_GoBytes(_cgo0, _cgo1); }()
		port := be16toh(uint16(sin4.sin_port))
		return fmt.Sprintf("%s:%d", net.IP(ip), port)
	} else if family == ( /*line :1547:22*/_Ciconst_AF_INET6 /*line :1547:31*/) {
		sin6 := (* /*line :1548:13*/_Ctype_struct_sockaddr_in6 /*line :1548:34*/)(unsafe.Pointer(sin))
		ip := func() []byte{ _cgoBase0 := /*line :1549:34*/&sin6.sin6_addr; _cgo0 := /*line :1549:19*/unsafe.Pointer(_cgoBase0); var _cgo1 _Ctype_int = /*line :1549:52*/16; _cgoCheckPointer(_cgoBase0, 0 == 0); return /*line :1549:55*/_Cfunc_GoBytes(_cgo0, _cgo1); }()
		port := be16toh(uint16(sin6.sin6_port))
		return fmt.Sprintf("[%s]:%d", net.IP(ip), port)
	}
	return "unknown"
}
